/*
 * SpinorML Ltd 🚀 AGPL-3.0 License - https://spinorml.com/license
 */

// C3k2 CUDA forward tests for the five remaining YOLO11n-n variants:
//
//   shortcut/  C3k2(32,  64,  c3k=F, shortcut=T, e=0.25)  — adds y1+m0out
//   deep_sf/   C3k2(128, 128, c3k=T, shortcut=F, e=0.5)   — c3k inner, no Add
//   deep_st/   C3k2(128, 128, c3k=T, shortcut=T, e=0.5)   — c3k inner + 2×Add
//   head_sf/   C3k2(384, 128, c3k=F, shortcut=F, e=0.5)   — wide input, no Add
//   head_st/   C3k2(384, 256, c3k=T, shortcut=T, e=0.5)   — wide input + c3k + 2×Add
//
// Spatial dims: B=2, H=4, W=4.  Fixtures generated by generate_all.py.

#[cfg(feature = "cuda")]
mod cuda {
    use dotenv::dotenv;
    use serial_test::serial;
    use teeny_compiler::compiler::{driver::cuda::compile_kernel, target::cuda::Target};
    use teeny_core::device::{Device, buffer::Buffer};
    use teeny_cuda::{device::CudaLaunchConfig, errors::Result, testing};

    const BATCH: usize = 2;
    const H: usize = 4;
    const W: usize = 4;
    const N_SPATIAL: usize = BATCH * H * W; // 32

    const BLOCK_OW: i32 = 4;
    const BLOCK_BN: i32 = 128;
    const BLOCK_SILU: i32 = 128;
    const BLOCK_CH: i32 = 128;
    const BLOCK_VADD: i32 = 128;
    const BN_EPS: f32 = 1e-5;
    const TOL: f32 = 1e-3;

    fn load(dir: &str, name: &str) -> Vec<f32> {
        let path = format!(
            "{}/tests/fixtures/c3k2_yolo26/{}/{}",
            env!("CARGO_MANIFEST_DIR"),
            dir,
            name
        );
        let bytes = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
        bytes
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect()
    }

    fn nchw_to_nc(src: &[f32], b: usize, c: usize, h: usize, w: usize) -> Vec<f32> {
        let mut out = vec![0.0f32; b * h * w * c];
        for bi in 0..b {
            for ci in 0..c {
                for hi in 0..h {
                    for wi in 0..w {
                        let ni = bi * h * w + hi * w + wi;
                        out[ni * c + ci] = src[bi * c * h * w + ci * h * w + hi * w + wi];
                    }
                }
            }
        }
        out
    }

    fn nc_to_nchw(src: &[f32], b: usize, c: usize, h: usize, w: usize) -> Vec<f32> {
        let mut out = vec![0.0f32; b * c * h * w];
        for bi in 0..b {
            for ci in 0..c {
                for hi in 0..h {
                    for wi in 0..w {
                        let ni = bi * h * w + hi * w + wi;
                        out[bi * c * h * w + ci * h * w + hi * w + wi] = src[ni * c + ci];
                    }
                }
            }
        }
        out
    }

    // ── Variant 2: shortcut ───────────────────────────────────────────────────
    //
    // C3k2(32, 64, n=1, c3k=False, shortcut=True, e=0.25)
    // c=16, c_inner=8.  Bottleneck adds y1 to its own output before cat.
    #[test]
    #[serial]
    fn test_c3k2_shortcut_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;
        let target = Target::new(env.capability);
        let dir = "shortcut";

        const C_IN: usize = 32;
        const C_OUT: usize = 64;
        const C: usize = 16;
        const C_INNER: usize = 8;
        const C_CAT: usize = 3 * C;

        const N_CV1: usize = N_SPATIAL * 2 * C;
        const N_HALF: usize = N_SPATIAL * C;
        const N_M0CV1: usize = N_SPATIAL * C_INNER;
        const N_M0CV2: usize = N_SPATIAL * C;
        const N_CAT: usize = N_SPATIAL * C_CAT;
        const N_CV2: usize = N_SPATIAL * C_OUT;

        let x_host = load(dir, "x.bin");
        let cv1_conv_w = load(dir, "cv1_conv_w.bin");
        let cv1_bn_w = load(dir, "cv1_bn_w.bin");
        let cv1_bn_b = load(dir, "cv1_bn_b.bin");
        let cv1_bn_rm = load(dir, "cv1_bn_rm.bin");
        let cv1_bn_rv = load(dir, "cv1_bn_rv.bin");
        let m0cv1_conv_w = load(dir, "m0_cv1_conv_w.bin");
        let m0cv1_bn_w = load(dir, "m0_cv1_bn_w.bin");
        let m0cv1_bn_b = load(dir, "m0_cv1_bn_b.bin");
        let m0cv1_bn_rm = load(dir, "m0_cv1_bn_rm.bin");
        let m0cv1_bn_rv = load(dir, "m0_cv1_bn_rv.bin");
        let m0cv2_conv_w = load(dir, "m0_cv2_conv_w.bin");
        let m0cv2_bn_w = load(dir, "m0_cv2_bn_w.bin");
        let m0cv2_bn_b = load(dir, "m0_cv2_bn_b.bin");
        let m0cv2_bn_rm = load(dir, "m0_cv2_bn_rm.bin");
        let m0cv2_bn_rv = load(dir, "m0_cv2_bn_rv.bin");
        let cv2_conv_w = load(dir, "cv2_conv_w.bin");
        let cv2_bn_w = load(dir, "cv2_bn_w.bin");
        let cv2_bn_b = load(dir, "cv2_bn_b.bin");
        let cv2_bn_rm = load(dir, "cv2_bn_rm.bin");
        let cv2_bn_rv = load(dir, "cv2_bn_rv.bin");
        let expected = load(dir, "expected_output.bin");

        // Compile kernels
        let conv1_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(1, 1, 1, 1, 0, 0, 1, BLOCK_OW),
            &target, true,
        )?)?;
        let conv1_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&conv1_ptx)?;

        let conv3_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(3, 3, 1, 1, 1, 1, 1, BLOCK_OW),
            &target, true,
        )?)?;
        let conv3_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&conv3_ptx)?;

        let bn_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference::<f32>::new(BLOCK_BN),
            &target, true,
        )?)?;
        let bn_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference<f32>,
        >(&bn_ptx)?;

        let silu_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::activation::sigmoid::SiluForward::new(BLOCK_SILU),
            &target, true,
        )?)?;
        let silu_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::activation::sigmoid::SiluForward,
        >(&silu_ptx)?;

        let chunk_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::tensor::channel_chunk::ChannelChunkForward::<f32>::new(BLOCK_CH),
            &target, true,
        )?)?;
        let chunk_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_chunk::ChannelChunkForward<f32>,
        >(&chunk_ptx)?;

        let cat_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::tensor::channel_cat::ChannelCatForward::<f32>::new(BLOCK_CH),
            &target, true,
        )?)?;
        let cat_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_cat::ChannelCatForward<f32>,
        >(&cat_ptx)?;

        let vadd_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::math::add::VectorAdd::<f32>::new(BLOCK_VADD),
            &target, true,
        )?)?;
        let vadd_prog = testing::load_program_from_ptx::<
            teeny_kernels::math::add::VectorAdd<f32>,
        >(&vadd_ptx)?;

        let ow_tiles = W.div_ceil(BLOCK_OW as usize);
        let bn_cfg = |c_ch: usize| CudaLaunchConfig {
            grid: [c_ch as u32, 1, 1], block: [1, 1, 1], cluster: [1, 1, 1],
        };
        let ch_cfg = CudaLaunchConfig {
            grid: [N_SPATIAL as u32, 1, 1],
            block: [BLOCK_CH as u32, 1, 1],
            cluster: [1, 1, 1],
        };

        // cv1 Conv(32→32, 1×1)
        let mut x_buf = device.buffer::<f32>(BATCH * C_IN * H * W)?;
        let mut cv1_cw = device.buffer::<f32>(2 * C * C_IN)?;
        let y_cv1_nchw = device.buffer::<f32>(N_CV1)?;
        x_buf.to_device(&x_host)?;
        cv1_cw.to_device(&cv1_conv_w)?;
        device.launch(&conv1_prog, &CudaLaunchConfig {
            grid: [(BATCH * 2 * C * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            x_buf.as_device_ptr() as *mut f32, cv1_cw.as_device_ptr() as *mut f32,
            y_cv1_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, C_IN as i32, (2 * C) as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut tmp = vec![0f32; N_CV1];
        y_cv1_nchw.to_host(&mut tmp)?;
        let cv1_nc_host = nchw_to_nc(&tmp, BATCH, 2 * C, H, W);

        // cv1 BN → SiLU
        let mut cv1_nc = device.buffer::<f32>(N_CV1)?;
        let cv1_bn_out = device.buffer::<f32>(N_CV1)?;
        let mut cv1_bnw = device.buffer::<f32>(2 * C)?;
        let mut cv1_bnb = device.buffer::<f32>(2 * C)?;
        let mut cv1_bnrm = device.buffer::<f32>(2 * C)?;
        let mut cv1_bnrv = device.buffer::<f32>(2 * C)?;
        cv1_nc.to_device(&cv1_nc_host)?;
        cv1_bnw.to_device(&cv1_bn_w)?;
        cv1_bnb.to_device(&cv1_bn_b)?;
        cv1_bnrm.to_device(&cv1_bn_rm)?;
        cv1_bnrv.to_device(&cv1_bn_rv)?;
        device.launch(&bn_prog, &bn_cfg(2 * C), (
            cv1_nc.as_device_ptr() as *mut f32, cv1_bn_out.as_device_ptr() as *mut f32,
            cv1_bnw.as_device_ptr() as *mut f32, cv1_bnb.as_device_ptr() as *mut f32,
            cv1_bnrm.as_device_ptr() as *mut f32, cv1_bnrv.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, (2 * C) as i32, BN_EPS,
        ))?;
        let cv1_silu = device.buffer::<f32>(N_CV1)?;
        device.launch(&silu_prog, &testing::launch_config(N_CV1, BLOCK_SILU), (
            cv1_bn_out.as_device_ptr() as *mut f32, cv1_silu.as_device_ptr() as *mut f32,
            N_CV1 as i32,
        ))?;

        // ChannelChunk → [y0, y1]
        let y0_buf = device.buffer::<f32>(N_HALF)?;
        let y1_buf = device.buffer::<f32>(N_HALF)?;
        device.launch(&chunk_prog, &ch_cfg, (
            cv1_silu.as_device_ptr() as *mut f32, y0_buf.as_device_ptr() as *mut f32,
            (2 * C) as i32, C as i32, 0i32,
        ))?;
        device.launch(&chunk_prog, &ch_cfg, (
            cv1_silu.as_device_ptr() as *mut f32, y1_buf.as_device_ptr() as *mut f32,
            (2 * C) as i32, C as i32, C as i32,
        ))?;

        // m0_cv1 Conv(16→8, 3×3)
        let mut y1_host = vec![0f32; N_HALF];
        y1_buf.to_host(&mut y1_host)?;
        let y1_nchw = nc_to_nchw(&y1_host, BATCH, C, H, W);
        let mut y1_nchw_buf = device.buffer::<f32>(N_HALF)?;
        let mut m0cw1 = device.buffer::<f32>(C_INNER * C * 9)?;
        let y_m0cv1_nchw = device.buffer::<f32>(N_M0CV1)?;
        y1_nchw_buf.to_device(&y1_nchw)?;
        m0cw1.to_device(&m0cv1_conv_w)?;
        device.launch(&conv3_prog, &CudaLaunchConfig {
            grid: [(BATCH * C_INNER * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            y1_nchw_buf.as_device_ptr() as *mut f32, m0cw1.as_device_ptr() as *mut f32,
            y_m0cv1_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, C as i32, C_INNER as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut tmp = vec![0f32; N_M0CV1];
        y_m0cv1_nchw.to_host(&mut tmp)?;
        let m0cv1_nc_host = nchw_to_nc(&tmp, BATCH, C_INNER, H, W);

        // m0_cv1 BN → SiLU
        let mut m0cv1_nc = device.buffer::<f32>(N_M0CV1)?;
        let m0cv1_bn_out = device.buffer::<f32>(N_M0CV1)?;
        let mut m0cv1_bnw = device.buffer::<f32>(C_INNER)?;
        let mut m0cv1_bnb = device.buffer::<f32>(C_INNER)?;
        let mut m0cv1_bnrm = device.buffer::<f32>(C_INNER)?;
        let mut m0cv1_bnrv = device.buffer::<f32>(C_INNER)?;
        m0cv1_nc.to_device(&m0cv1_nc_host)?;
        m0cv1_bnw.to_device(&m0cv1_bn_w)?;
        m0cv1_bnb.to_device(&m0cv1_bn_b)?;
        m0cv1_bnrm.to_device(&m0cv1_bn_rm)?;
        m0cv1_bnrv.to_device(&m0cv1_bn_rv)?;
        device.launch(&bn_prog, &bn_cfg(C_INNER), (
            m0cv1_nc.as_device_ptr() as *mut f32, m0cv1_bn_out.as_device_ptr() as *mut f32,
            m0cv1_bnw.as_device_ptr() as *mut f32, m0cv1_bnb.as_device_ptr() as *mut f32,
            m0cv1_bnrm.as_device_ptr() as *mut f32, m0cv1_bnrv.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, C_INNER as i32, BN_EPS,
        ))?;
        let m0cv1_silu = device.buffer::<f32>(N_M0CV1)?;
        device.launch(&silu_prog, &testing::launch_config(N_M0CV1, BLOCK_SILU), (
            m0cv1_bn_out.as_device_ptr() as *mut f32, m0cv1_silu.as_device_ptr() as *mut f32,
            N_M0CV1 as i32,
        ))?;

        // m0_cv2 Conv(8→16, 3×3)
        let mut m0cv1_silu_host = vec![0f32; N_M0CV1];
        m0cv1_silu.to_host(&mut m0cv1_silu_host)?;
        let m0cv1_silu_nchw = nc_to_nchw(&m0cv1_silu_host, BATCH, C_INNER, H, W);
        let mut m0cv1_silu_nchw_buf = device.buffer::<f32>(N_M0CV1)?;
        let mut m0cw2 = device.buffer::<f32>(C * C_INNER * 9)?;
        let y_m0cv2_nchw = device.buffer::<f32>(N_M0CV2)?;
        m0cv1_silu_nchw_buf.to_device(&m0cv1_silu_nchw)?;
        m0cw2.to_device(&m0cv2_conv_w)?;
        device.launch(&conv3_prog, &CudaLaunchConfig {
            grid: [(BATCH * C * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            m0cv1_silu_nchw_buf.as_device_ptr() as *mut f32, m0cw2.as_device_ptr() as *mut f32,
            y_m0cv2_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, C_INNER as i32, C as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut tmp = vec![0f32; N_M0CV2];
        y_m0cv2_nchw.to_host(&mut tmp)?;
        let m0cv2_nc_host = nchw_to_nc(&tmp, BATCH, C, H, W);

        // m0_cv2 BN → SiLU
        let mut m0cv2_nc = device.buffer::<f32>(N_M0CV2)?;
        let m0cv2_bn_out = device.buffer::<f32>(N_M0CV2)?;
        let mut m0cv2_bnw = device.buffer::<f32>(C)?;
        let mut m0cv2_bnb = device.buffer::<f32>(C)?;
        let mut m0cv2_bnrm = device.buffer::<f32>(C)?;
        let mut m0cv2_bnrv = device.buffer::<f32>(C)?;
        m0cv2_nc.to_device(&m0cv2_nc_host)?;
        m0cv2_bnw.to_device(&m0cv2_bn_w)?;
        m0cv2_bnb.to_device(&m0cv2_bn_b)?;
        m0cv2_bnrm.to_device(&m0cv2_bn_rm)?;
        m0cv2_bnrv.to_device(&m0cv2_bn_rv)?;
        device.launch(&bn_prog, &bn_cfg(C), (
            m0cv2_nc.as_device_ptr() as *mut f32, m0cv2_bn_out.as_device_ptr() as *mut f32,
            m0cv2_bnw.as_device_ptr() as *mut f32, m0cv2_bnb.as_device_ptr() as *mut f32,
            m0cv2_bnrm.as_device_ptr() as *mut f32, m0cv2_bnrv.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, C as i32, BN_EPS,
        ))?;
        let m0cv2_silu = device.buffer::<f32>(N_M0CV2)?;
        device.launch(&silu_prog, &testing::launch_config(N_M0CV2, BLOCK_SILU), (
            m0cv2_bn_out.as_device_ptr() as *mut f32, m0cv2_silu.as_device_ptr() as *mut f32,
            N_M0CV2 as i32,
        ))?;

        // Shortcut: m0_out = y1 + m0cv2_silu
        let m0_out = device.buffer::<f32>(N_M0CV2)?;
        device.launch(&vadd_prog, &testing::launch_config(N_M0CV2, BLOCK_VADD), (
            y1_buf.as_device_ptr() as *mut f32,
            m0cv2_silu.as_device_ptr() as *mut f32,
            m0_out.as_device_ptr() as *mut f32,
            N_M0CV2 as i32,
        ))?;

        // ChannelCat([y0, y1, m0_out]) → 48 channels
        let cat_buf = device.buffer::<f32>(N_CAT)?;
        device.launch(&cat_prog, &ch_cfg, (
            y0_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            C as i32, C_CAT as i32, 0i32,
        ))?;
        device.launch(&cat_prog, &ch_cfg, (
            y1_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            C as i32, C_CAT as i32, C as i32,
        ))?;
        device.launch(&cat_prog, &ch_cfg, (
            m0_out.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            C as i32, C_CAT as i32, (2 * C) as i32,
        ))?;

        // cv2 Conv(48→64, 1×1)
        let mut cat_host = vec![0f32; N_CAT];
        cat_buf.to_host(&mut cat_host)?;
        let cat_nchw = nc_to_nchw(&cat_host, BATCH, C_CAT, H, W);
        let mut cat_nchw_buf = device.buffer::<f32>(N_CAT)?;
        let mut cv2_cw = device.buffer::<f32>(C_OUT * C_CAT)?;
        let y_cv2_nchw = device.buffer::<f32>(N_CV2)?;
        cat_nchw_buf.to_device(&cat_nchw)?;
        cv2_cw.to_device(&cv2_conv_w)?;
        device.launch(&conv1_prog, &CudaLaunchConfig {
            grid: [(BATCH * C_OUT * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            cat_nchw_buf.as_device_ptr() as *mut f32, cv2_cw.as_device_ptr() as *mut f32,
            y_cv2_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, C_CAT as i32, C_OUT as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut tmp = vec![0f32; N_CV2];
        y_cv2_nchw.to_host(&mut tmp)?;
        let cv2_nc_host = nchw_to_nc(&tmp, BATCH, C_OUT, H, W);

        // cv2 BN → SiLU
        let mut cv2_nc = device.buffer::<f32>(N_CV2)?;
        let cv2_bn_out = device.buffer::<f32>(N_CV2)?;
        let mut cv2_bnw = device.buffer::<f32>(C_OUT)?;
        let mut cv2_bnb = device.buffer::<f32>(C_OUT)?;
        let mut cv2_bnrm = device.buffer::<f32>(C_OUT)?;
        let mut cv2_bnrv = device.buffer::<f32>(C_OUT)?;
        cv2_nc.to_device(&cv2_nc_host)?;
        cv2_bnw.to_device(&cv2_bn_w)?;
        cv2_bnb.to_device(&cv2_bn_b)?;
        cv2_bnrm.to_device(&cv2_bn_rm)?;
        cv2_bnrv.to_device(&cv2_bn_rv)?;
        device.launch(&bn_prog, &bn_cfg(C_OUT), (
            cv2_nc.as_device_ptr() as *mut f32, cv2_bn_out.as_device_ptr() as *mut f32,
            cv2_bnw.as_device_ptr() as *mut f32, cv2_bnb.as_device_ptr() as *mut f32,
            cv2_bnrm.as_device_ptr() as *mut f32, cv2_bnrv.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, C_OUT as i32, BN_EPS,
        ))?;
        let cv2_silu = device.buffer::<f32>(N_CV2)?;
        device.launch(&silu_prog, &testing::launch_config(N_CV2, BLOCK_SILU), (
            cv2_bn_out.as_device_ptr() as *mut f32, cv2_silu.as_device_ptr() as *mut f32,
            N_CV2 as i32,
        ))?;

        let mut y_nc = vec![0f32; N_CV2];
        cv2_silu.to_host(&mut y_nc)?;
        let expected_nc = nchw_to_nc(&expected, BATCH, C_OUT, H, W);
        for i in 0..N_CV2 {
            assert!(
                (y_nc[i] - expected_nc[i]).abs() < TOL,
                "shortcut mismatch at {i}: gpu={} expected={}",
                y_nc[i], expected_nc[i],
            );
        }
        Ok(())
    }

    // ── Variant 3 & 4: deep (c3k=True) ───────────────────────────────────────
    //
    // Shared inner helper: runs the c3k inner block on y1_nc and returns c3k_out_nc.
    // c3k_inner flow:
    //   icv1(y1, 1×1) → BN → SiLU → a
    //   m0_cv1(a,  3×3) → BN → SiLU → b
    //   m0_cv2(b,  3×3) → BN → SiLU → m0_out   [+ a if shortcut]
    //   m1_cv1(m0_out, 3×3) → BN → SiLU → c
    //   m1_cv2(c,  3×3) → BN → SiLU → h1       [+ m0_out if shortcut]
    //   icv2(y1, 1×1) → BN → SiLU → h2
    //   inner_cat([h1, h2]) → icv3(1×1) → BN → SiLU → c3k_out

    // C3k2(128, 128, n=1, c3k=True, shortcut=False, e=0.5)
    #[test]
    #[serial]
    fn test_c3k2_deep_sf_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;
        let target = Target::new(env.capability);
        run_c3k2_true_forward(&device, &target, "deep_sf", 128, 128, 64, 32, false)
    }

    // C3k2(128, 128, n=1, c3k=True, shortcut=True, e=0.5)
    #[test]
    #[serial]
    fn test_c3k2_deep_st_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;
        let target = Target::new(env.capability);
        run_c3k2_true_forward(&device, &target, "deep_st", 128, 128, 64, 32, true)
    }

    // C3k2(384, 256, n=1, c3k=True, shortcut=True, e=0.5)
    #[test]
    #[serial]
    fn test_c3k2_head_st_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;
        let target = Target::new(env.capability);
        run_c3k2_true_forward(&device, &target, "head_st", 384, 256, 128, 64, true)
    }

    /// Runs C3k2 with c3k=True forward pass and checks against fixture.
    /// c: outer hidden (= c_out * e), c_h: inner hidden (= c * 0.5).
    fn run_c3k2_true_forward(
        device: &teeny_cuda::device::CudaDevice,
        target: &Target,
        dir: &str,
        c_in: usize,
        c_out: usize,
        c: usize,       // outer hidden dim
        c_h: usize,     // c3k inner hidden dim
        shortcut: bool,
    ) -> Result<()> {
        let n_cv1        = N_SPATIAL * 2 * c;
        let n_half       = N_SPATIAL * c;
        let n_icvout     = N_SPATIAL * c_h;      // icv1/icv2/bottleneck outputs
        let n_inner_cat  = N_SPATIAL * 2 * c_h;  // cat([h1,h2]) inside c3k
        let _n_c3k_out   = N_SPATIAL * c;
        let n_outer_cat  = N_SPATIAL * 3 * c;     // outer cat [y0,y1,c3k_out]
        let n_cv2        = N_SPATIAL * c_out;

        // Load all fixtures
        let x_host       = load(dir, "x.bin");
        let cv1_cw       = load(dir, "cv1_conv_w.bin");
        let cv1_bnw      = load(dir, "cv1_bn_w.bin");
        let cv1_bnb      = load(dir, "cv1_bn_b.bin");
        let cv1_bnrm     = load(dir, "cv1_bn_rm.bin");
        let cv1_bnrv     = load(dir, "cv1_bn_rv.bin");
        let icv1_cw      = load(dir, "m0_icv1_conv_w.bin");
        let icv1_bnw     = load(dir, "m0_icv1_bn_w.bin");
        let icv1_bnb     = load(dir, "m0_icv1_bn_b.bin");
        let icv1_bnrm    = load(dir, "m0_icv1_bn_rm.bin");
        let icv1_bnrv    = load(dir, "m0_icv1_bn_rv.bin");
        let icv2_cw      = load(dir, "m0_icv2_conv_w.bin");
        let icv2_bnw     = load(dir, "m0_icv2_bn_w.bin");
        let icv2_bnb     = load(dir, "m0_icv2_bn_b.bin");
        let icv2_bnrm    = load(dir, "m0_icv2_bn_rm.bin");
        let icv2_bnrv    = load(dir, "m0_icv2_bn_rv.bin");
        let icv3_cw      = load(dir, "m0_icv3_conv_w.bin");
        let icv3_bnw     = load(dir, "m0_icv3_bn_w.bin");
        let icv3_bnb     = load(dir, "m0_icv3_bn_b.bin");
        let icv3_bnrm    = load(dir, "m0_icv3_bn_rm.bin");
        let icv3_bnrv    = load(dir, "m0_icv3_bn_rv.bin");
        let m0cv1_cw     = load(dir, "m0_m0_cv1_conv_w.bin");
        let m0cv1_bnw    = load(dir, "m0_m0_cv1_bn_w.bin");
        let m0cv1_bnb    = load(dir, "m0_m0_cv1_bn_b.bin");
        let m0cv1_bnrm   = load(dir, "m0_m0_cv1_bn_rm.bin");
        let m0cv1_bnrv   = load(dir, "m0_m0_cv1_bn_rv.bin");
        let m0cv2_cw     = load(dir, "m0_m0_cv2_conv_w.bin");
        let m0cv2_bnw    = load(dir, "m0_m0_cv2_bn_w.bin");
        let m0cv2_bnb    = load(dir, "m0_m0_cv2_bn_b.bin");
        let m0cv2_bnrm   = load(dir, "m0_m0_cv2_bn_rm.bin");
        let m0cv2_bnrv   = load(dir, "m0_m0_cv2_bn_rv.bin");
        let m1cv1_cw     = load(dir, "m0_m1_cv1_conv_w.bin");
        let m1cv1_bnw    = load(dir, "m0_m1_cv1_bn_w.bin");
        let m1cv1_bnb    = load(dir, "m0_m1_cv1_bn_b.bin");
        let m1cv1_bnrm   = load(dir, "m0_m1_cv1_bn_rm.bin");
        let m1cv1_bnrv   = load(dir, "m0_m1_cv1_bn_rv.bin");
        let m1cv2_cw     = load(dir, "m0_m1_cv2_conv_w.bin");
        let m1cv2_bnw    = load(dir, "m0_m1_cv2_bn_w.bin");
        let m1cv2_bnb    = load(dir, "m0_m1_cv2_bn_b.bin");
        let m1cv2_bnrm   = load(dir, "m0_m1_cv2_bn_rm.bin");
        let m1cv2_bnrv   = load(dir, "m0_m1_cv2_bn_rv.bin");
        let outer_cv2_cw = load(dir, "cv2_conv_w.bin");
        let outer_cv2_bnw= load(dir, "cv2_bn_w.bin");
        let outer_cv2_bnb= load(dir, "cv2_bn_b.bin");
        let outer_cv2_bnrm=load(dir, "cv2_bn_rm.bin");
        let outer_cv2_bnrv=load(dir, "cv2_bn_rv.bin");
        let expected     = load(dir, "expected_output.bin");

        // Compile kernels
        let conv1_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(1, 1, 1, 1, 0, 0, 1, BLOCK_OW),
            target, true,
        )?)?;
        let conv1_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&conv1_ptx)?;

        let conv3_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(3, 3, 1, 1, 1, 1, 1, BLOCK_OW),
            target, true,
        )?)?;
        let conv3_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&conv3_ptx)?;

        let bn_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference::<f32>::new(BLOCK_BN),
            target, true,
        )?)?;
        let bn_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference<f32>,
        >(&bn_ptx)?;

        let silu_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::activation::sigmoid::SiluForward::new(BLOCK_SILU),
            target, true,
        )?)?;
        let silu_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::activation::sigmoid::SiluForward,
        >(&silu_ptx)?;

        let chunk_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::tensor::channel_chunk::ChannelChunkForward::<f32>::new(BLOCK_CH),
            target, true,
        )?)?;
        let chunk_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_chunk::ChannelChunkForward<f32>,
        >(&chunk_ptx)?;

        let cat_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::tensor::channel_cat::ChannelCatForward::<f32>::new(BLOCK_CH),
            target, true,
        )?)?;
        let cat_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_cat::ChannelCatForward<f32>,
        >(&cat_ptx)?;

        let vadd_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::math::add::VectorAdd::<f32>::new(BLOCK_VADD),
            target, true,
        )?)?;
        let vadd_prog = testing::load_program_from_ptx::<
            teeny_kernels::math::add::VectorAdd<f32>,
        >(&vadd_ptx)?;

        let ow_tiles = W.div_ceil(BLOCK_OW as usize);

        // Shorthand closures for launch configs
        let conv1_cfg = |cout: usize| CudaLaunchConfig {
            grid: [(BATCH * cout * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        };
        let conv3_cfg = |cout: usize| CudaLaunchConfig {
            grid: [(BATCH * cout * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        };
        let bn_cfg = |c_ch: usize| CudaLaunchConfig {
            grid: [c_ch as u32, 1, 1], block: [1, 1, 1], cluster: [1, 1, 1],
        };
        let ch_cfg = |n: usize| CudaLaunchConfig {
            grid: [n as u32, 1, 1],
            block: [BLOCK_CH as u32, 1, 1],
            cluster: [1, 1, 1],
        };

        // Helper: Conv(k=1) → BN → SiLU, returns NC output (device buffer)
        macro_rules! conv1_bn_silu {
            ($x_nchw:expr, $w:expr, $cin:expr, $cout:expr,
             $bnw:expr, $bnb:expr, $bnrm:expr, $bnrv:expr) => {{
                let n_out = N_SPATIAL * $cout;
                let mut w_buf = device.buffer::<f32>($w.len())?;
                let y_nchw = device.buffer::<f32>(BATCH * $cout * H * W)?;
                w_buf.to_device($w)?;
                device.launch(&conv1_prog, &conv1_cfg($cout), (
                    $x_nchw.as_device_ptr() as *mut f32,
                    w_buf.as_device_ptr() as *mut f32,
                    y_nchw.as_device_ptr() as *mut f32,
                    BATCH as i32, $cin as i32, $cout as i32,
                    H as i32, W as i32, H as i32, W as i32,
                ))?;
                let mut tmp = vec![0f32; BATCH * $cout * H * W];
                y_nchw.to_host(&mut tmp)?;
                let nc_host = nchw_to_nc(&tmp, BATCH, $cout, H, W);
                let mut nc_buf = device.buffer::<f32>(n_out)?;
                let bn_out = device.buffer::<f32>(n_out)?;
                let mut bnw_buf = device.buffer::<f32>($cout)?;
                let mut bnb_buf = device.buffer::<f32>($cout)?;
                let mut bnrm_buf = device.buffer::<f32>($cout)?;
                let mut bnrv_buf = device.buffer::<f32>($cout)?;
                nc_buf.to_device(&nc_host)?;
                bnw_buf.to_device($bnw)?;
                bnb_buf.to_device($bnb)?;
                bnrm_buf.to_device($bnrm)?;
                bnrv_buf.to_device($bnrv)?;
                device.launch(&bn_prog, &bn_cfg($cout), (
                    nc_buf.as_device_ptr() as *mut f32,
                    bn_out.as_device_ptr() as *mut f32,
                    bnw_buf.as_device_ptr() as *mut f32,
                    bnb_buf.as_device_ptr() as *mut f32,
                    bnrm_buf.as_device_ptr() as *mut f32,
                    bnrv_buf.as_device_ptr() as *mut f32,
                    N_SPATIAL as i32, $cout as i32, BN_EPS,
                ))?;
                let silu_out = device.buffer::<f32>(n_out)?;
                device.launch(&silu_prog, &testing::launch_config(n_out, BLOCK_SILU), (
                    bn_out.as_device_ptr() as *mut f32,
                    silu_out.as_device_ptr() as *mut f32,
                    n_out as i32,
                ))?;
                silu_out
            }};
        }

        // Helper: Conv(k=3,p=1) → BN → SiLU, returns NC output (device buffer)
        macro_rules! conv3_bn_silu {
            ($x_nchw:expr, $w:expr, $cin:expr, $cout:expr,
             $bnw:expr, $bnb:expr, $bnrm:expr, $bnrv:expr) => {{
                let n_out = N_SPATIAL * $cout;
                let mut w_buf = device.buffer::<f32>($w.len())?;
                let y_nchw = device.buffer::<f32>(BATCH * $cout * H * W)?;
                w_buf.to_device($w)?;
                device.launch(&conv3_prog, &conv3_cfg($cout), (
                    $x_nchw.as_device_ptr() as *mut f32,
                    w_buf.as_device_ptr() as *mut f32,
                    y_nchw.as_device_ptr() as *mut f32,
                    BATCH as i32, $cin as i32, $cout as i32,
                    H as i32, W as i32, H as i32, W as i32,
                ))?;
                let mut tmp = vec![0f32; BATCH * $cout * H * W];
                y_nchw.to_host(&mut tmp)?;
                let nc_host = nchw_to_nc(&tmp, BATCH, $cout, H, W);
                let mut nc_buf = device.buffer::<f32>(n_out)?;
                let bn_out = device.buffer::<f32>(n_out)?;
                let mut bnw_buf = device.buffer::<f32>($cout)?;
                let mut bnb_buf = device.buffer::<f32>($cout)?;
                let mut bnrm_buf = device.buffer::<f32>($cout)?;
                let mut bnrv_buf = device.buffer::<f32>($cout)?;
                nc_buf.to_device(&nc_host)?;
                bnw_buf.to_device($bnw)?;
                bnb_buf.to_device($bnb)?;
                bnrm_buf.to_device($bnrm)?;
                bnrv_buf.to_device($bnrv)?;
                device.launch(&bn_prog, &bn_cfg($cout), (
                    nc_buf.as_device_ptr() as *mut f32,
                    bn_out.as_device_ptr() as *mut f32,
                    bnw_buf.as_device_ptr() as *mut f32,
                    bnb_buf.as_device_ptr() as *mut f32,
                    bnrm_buf.as_device_ptr() as *mut f32,
                    bnrv_buf.as_device_ptr() as *mut f32,
                    N_SPATIAL as i32, $cout as i32, BN_EPS,
                ))?;
                let silu_out = device.buffer::<f32>(n_out)?;
                device.launch(&silu_prog, &testing::launch_config(n_out, BLOCK_SILU), (
                    bn_out.as_device_ptr() as *mut f32,
                    silu_out.as_device_ptr() as *mut f32,
                    n_out as i32,
                ))?;
                silu_out
            }};
        }

        // Helper: NC → NCHW device buffer
        macro_rules! to_nchw_buf {
            ($nc_buf:expr, $c:expr) => {{
                let mut host = vec![0f32; BATCH * $c * H * W];
                $nc_buf.to_host(&mut host)?;
                let nchw = nc_to_nchw(&host, BATCH, $c, H, W);
                let mut buf = device.buffer::<f32>(BATCH * $c * H * W)?;
                buf.to_device(&nchw)?;
                buf
            }};
        }

        // ── outer cv1: Conv(c_in → 2*c, 1×1) ───────────────────────────────────
        let mut x_buf = device.buffer::<f32>(BATCH * c_in * H * W)?;
        x_buf.to_device(&x_host)?;
        let mut cv1_cw_buf = device.buffer::<f32>(cv1_cw.len())?;
        let y_cv1_nchw = device.buffer::<f32>(n_cv1)?;
        cv1_cw_buf.to_device(&cv1_cw)?;
        device.launch(&conv1_prog, &conv1_cfg(2 * c), (
            x_buf.as_device_ptr() as *mut f32,
            cv1_cw_buf.as_device_ptr() as *mut f32,
            y_cv1_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, c_in as i32, (2 * c) as i32,
            H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut tmp = vec![0f32; n_cv1];
        y_cv1_nchw.to_host(&mut tmp)?;
        let cv1_nc_host = nchw_to_nc(&tmp, BATCH, 2 * c, H, W);
        let mut cv1_nc_buf = device.buffer::<f32>(n_cv1)?;
        let cv1_bn_out = device.buffer::<f32>(n_cv1)?;
        let mut cv1_bnw_buf = device.buffer::<f32>(2 * c)?;
        let mut cv1_bnb_buf = device.buffer::<f32>(2 * c)?;
        let mut cv1_bnrm_buf = device.buffer::<f32>(2 * c)?;
        let mut cv1_bnrv_buf = device.buffer::<f32>(2 * c)?;
        cv1_nc_buf.to_device(&cv1_nc_host)?;
        cv1_bnw_buf.to_device(&cv1_bnw)?;
        cv1_bnb_buf.to_device(&cv1_bnb)?;
        cv1_bnrm_buf.to_device(&cv1_bnrm)?;
        cv1_bnrv_buf.to_device(&cv1_bnrv)?;
        device.launch(&bn_prog, &bn_cfg(2 * c), (
            cv1_nc_buf.as_device_ptr() as *mut f32,
            cv1_bn_out.as_device_ptr() as *mut f32,
            cv1_bnw_buf.as_device_ptr() as *mut f32,
            cv1_bnb_buf.as_device_ptr() as *mut f32,
            cv1_bnrm_buf.as_device_ptr() as *mut f32,
            cv1_bnrv_buf.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, (2 * c) as i32, BN_EPS,
        ))?;
        let cv1_silu = device.buffer::<f32>(n_cv1)?;
        device.launch(&silu_prog, &testing::launch_config(n_cv1, BLOCK_SILU), (
            cv1_bn_out.as_device_ptr() as *mut f32,
            cv1_silu.as_device_ptr() as *mut f32,
            n_cv1 as i32,
        ))?;

        // outer ChannelChunk → [y0, y1]
        let y0_buf = device.buffer::<f32>(n_half)?;
        let y1_buf = device.buffer::<f32>(n_half)?;
        device.launch(&chunk_prog, &ch_cfg(N_SPATIAL), (
            cv1_silu.as_device_ptr() as *mut f32,
            y0_buf.as_device_ptr() as *mut f32,
            (2 * c) as i32, c as i32, 0i32,
        ))?;
        device.launch(&chunk_prog, &ch_cfg(N_SPATIAL), (
            cv1_silu.as_device_ptr() as *mut f32,
            y1_buf.as_device_ptr() as *mut f32,
            (2 * c) as i32, c as i32, c as i32,
        ))?;

        // ── c3k_inner(y1) ────────────────────────────────────────────────────
        // icv1: Conv(c → c_h, 1×1)
        let y1_nchw_buf = to_nchw_buf!(y1_buf, c);
        let icv1_silu = conv1_bn_silu!(
            y1_nchw_buf, &icv1_cw, c, c_h,
            &icv1_bnw, &icv1_bnb, &icv1_bnrm, &icv1_bnrv
        );

        // m0_cv1: Conv(c_h → c_h, 3×3)
        let icv1_nchw = to_nchw_buf!(icv1_silu, c_h);
        let m0cv1_silu = conv3_bn_silu!(
            icv1_nchw, &m0cv1_cw, c_h, c_h,
            &m0cv1_bnw, &m0cv1_bnb, &m0cv1_bnrm, &m0cv1_bnrv
        );

        // m0_cv2: Conv(c_h → c_h, 3×3)
        let m0cv1_nchw = to_nchw_buf!(m0cv1_silu, c_h);
        let m0cv2_silu = conv3_bn_silu!(
            m0cv1_nchw, &m0cv2_cw, c_h, c_h,
            &m0cv2_bnw, &m0cv2_bnb, &m0cv2_bnrm, &m0cv2_bnrv
        );

        // m0 shortcut: m0_out = icv1_silu + m0cv2_silu  (or just m0cv2_silu)
        let m0_out = if shortcut {
            let out = device.buffer::<f32>(n_icvout)?;
            device.launch(&vadd_prog, &testing::launch_config(n_icvout, BLOCK_VADD), (
                icv1_silu.as_device_ptr() as *mut f32,
                m0cv2_silu.as_device_ptr() as *mut f32,
                out.as_device_ptr() as *mut f32,
                n_icvout as i32,
            ))?;
            out
        } else {
            m0cv2_silu
        };

        // m1_cv1: Conv(c_h → c_h, 3×3)
        let m0_out_nchw = to_nchw_buf!(m0_out, c_h);
        let m1cv1_silu = conv3_bn_silu!(
            m0_out_nchw, &m1cv1_cw, c_h, c_h,
            &m1cv1_bnw, &m1cv1_bnb, &m1cv1_bnrm, &m1cv1_bnrv
        );

        // m1_cv2: Conv(c_h → c_h, 3×3)
        let m1cv1_nchw = to_nchw_buf!(m1cv1_silu, c_h);
        let m1cv2_silu = conv3_bn_silu!(
            m1cv1_nchw, &m1cv2_cw, c_h, c_h,
            &m1cv2_bnw, &m1cv2_bnb, &m1cv2_bnrm, &m1cv2_bnrv
        );

        // m1 shortcut: h1 = m0_out (NC) + m1cv2_silu  (or just m1cv2_silu)
        let h1 = if shortcut {
            let out = device.buffer::<f32>(n_icvout)?;
            device.launch(&vadd_prog, &testing::launch_config(n_icvout, BLOCK_VADD), (
                m0_out.as_device_ptr() as *mut f32,
                m1cv2_silu.as_device_ptr() as *mut f32,
                out.as_device_ptr() as *mut f32,
                n_icvout as i32,
            ))?;
            out
        } else {
            m1cv2_silu
        };

        // icv2: Conv(c → c_h, 1×1) applied to y1 (same as icv1's input)
        let y1_nchw_buf2 = to_nchw_buf!(y1_buf, c);
        let h2 = conv1_bn_silu!(
            y1_nchw_buf2, &icv2_cw, c, c_h,
            &icv2_bnw, &icv2_bnb, &icv2_bnrm, &icv2_bnrv
        );

        // inner ChannelCat([h1, h2]) → 2*c_h channels
        let inner_cat = device.buffer::<f32>(n_inner_cat)?;
        device.launch(&cat_prog, &ch_cfg(N_SPATIAL), (
            h1.as_device_ptr() as *mut f32,
            inner_cat.as_device_ptr() as *mut f32,
            c_h as i32, (2 * c_h) as i32, 0i32,
        ))?;
        device.launch(&cat_prog, &ch_cfg(N_SPATIAL), (
            h2.as_device_ptr() as *mut f32,
            inner_cat.as_device_ptr() as *mut f32,
            c_h as i32, (2 * c_h) as i32, c_h as i32,
        ))?;

        // icv3: Conv(2*c_h → c, 1×1)
        let inner_cat_nchw = to_nchw_buf!(inner_cat, 2 * c_h);
        let c3k_out = conv1_bn_silu!(
            inner_cat_nchw, &icv3_cw, 2 * c_h, c,
            &icv3_bnw, &icv3_bnb, &icv3_bnrm, &icv3_bnrv
        );

        // ── outer ChannelCat([y0, y1, c3k_out]) ─────────────────────────────
        let outer_cat = device.buffer::<f32>(n_outer_cat)?;
        device.launch(&cat_prog, &ch_cfg(N_SPATIAL), (
            y0_buf.as_device_ptr() as *mut f32,
            outer_cat.as_device_ptr() as *mut f32,
            c as i32, (3 * c) as i32, 0i32,
        ))?;
        device.launch(&cat_prog, &ch_cfg(N_SPATIAL), (
            y1_buf.as_device_ptr() as *mut f32,
            outer_cat.as_device_ptr() as *mut f32,
            c as i32, (3 * c) as i32, c as i32,
        ))?;
        device.launch(&cat_prog, &ch_cfg(N_SPATIAL), (
            c3k_out.as_device_ptr() as *mut f32,
            outer_cat.as_device_ptr() as *mut f32,
            c as i32, (3 * c) as i32, (2 * c) as i32,
        ))?;

        // outer cv2: Conv(3*c → c_out, 1×1)
        let outer_cat_nchw = to_nchw_buf!(outer_cat, 3 * c);
        let cv2_out = conv1_bn_silu!(
            outer_cat_nchw, &outer_cv2_cw, 3 * c, c_out,
            &outer_cv2_bnw, &outer_cv2_bnb, &outer_cv2_bnrm, &outer_cv2_bnrv
        );

        let mut y_nc = vec![0f32; n_cv2];
        cv2_out.to_host(&mut y_nc)?;
        let expected_nc = nchw_to_nc(&expected, BATCH, c_out, H, W);
        for i in 0..n_cv2 {
            assert!(
                (y_nc[i] - expected_nc[i]).abs() < TOL,
                "{dir} mismatch at {i}: gpu={} expected={}",
                y_nc[i], expected_nc[i],
            );
        }
        Ok(())
    }

    // ── Variant 5: head_sf ────────────────────────────────────────────────────
    //
    // C3k2(384, 128, n=1, c3k=False, shortcut=False, e=0.5)
    // c=64, c_inner=32.  Same topology as base but wider.
    #[test]
    #[serial]
    fn test_c3k2_head_sf_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;
        let target = Target::new(env.capability);
        let dir = "head_sf";

        const C_IN: usize = 384;
        const C_OUT: usize = 128;
        const C: usize = 64;
        const C_INNER: usize = 32;
        const C_CAT: usize = 3 * C; // 192

        const N_CV1: usize = N_SPATIAL * 2 * C;       // 32 * 128 = 4096
        const N_HALF: usize = N_SPATIAL * C;           // 32 * 64  = 2048
        const N_M0CV1: usize = N_SPATIAL * C_INNER;   // 32 * 32  = 1024
        const N_M0CV2: usize = N_SPATIAL * C;          // 32 * 64  = 2048
        const N_CAT: usize = N_SPATIAL * C_CAT;        // 32 * 192 = 6144
        const N_CV2: usize = N_SPATIAL * C_OUT;        // 32 * 128 = 4096

        let x_host       = load(dir, "x.bin");
        let cv1_conv_w   = load(dir, "cv1_conv_w.bin");
        let cv1_bn_w     = load(dir, "cv1_bn_w.bin");
        let cv1_bn_b     = load(dir, "cv1_bn_b.bin");
        let cv1_bn_rm    = load(dir, "cv1_bn_rm.bin");
        let cv1_bn_rv    = load(dir, "cv1_bn_rv.bin");
        let m0cv1_conv_w = load(dir, "m0_cv1_conv_w.bin");
        let m0cv1_bn_w   = load(dir, "m0_cv1_bn_w.bin");
        let m0cv1_bn_b   = load(dir, "m0_cv1_bn_b.bin");
        let m0cv1_bn_rm  = load(dir, "m0_cv1_bn_rm.bin");
        let m0cv1_bn_rv  = load(dir, "m0_cv1_bn_rv.bin");
        let m0cv2_conv_w = load(dir, "m0_cv2_conv_w.bin");
        let m0cv2_bn_w   = load(dir, "m0_cv2_bn_w.bin");
        let m0cv2_bn_b   = load(dir, "m0_cv2_bn_b.bin");
        let m0cv2_bn_rm  = load(dir, "m0_cv2_bn_rm.bin");
        let m0cv2_bn_rv  = load(dir, "m0_cv2_bn_rv.bin");
        let cv2_conv_w   = load(dir, "cv2_conv_w.bin");
        let cv2_bn_w     = load(dir, "cv2_bn_w.bin");
        let cv2_bn_b     = load(dir, "cv2_bn_b.bin");
        let cv2_bn_rm    = load(dir, "cv2_bn_rm.bin");
        let cv2_bn_rv    = load(dir, "cv2_bn_rv.bin");
        let expected     = load(dir, "expected_output.bin");

        let conv1_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(1, 1, 1, 1, 0, 0, 1, BLOCK_OW),
            &target, true,
        )?)?;
        let conv1_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&conv1_ptx)?;

        let conv3_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(3, 3, 1, 1, 1, 1, 1, BLOCK_OW),
            &target, true,
        )?)?;
        let conv3_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&conv3_ptx)?;

        let bn_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference::<f32>::new(BLOCK_BN),
            &target, true,
        )?)?;
        let bn_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference<f32>,
        >(&bn_ptx)?;

        let silu_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::activation::sigmoid::SiluForward::new(BLOCK_SILU),
            &target, true,
        )?)?;
        let silu_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::activation::sigmoid::SiluForward,
        >(&silu_ptx)?;

        let chunk_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::tensor::channel_chunk::ChannelChunkForward::<f32>::new(BLOCK_CH),
            &target, true,
        )?)?;
        let chunk_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_chunk::ChannelChunkForward<f32>,
        >(&chunk_ptx)?;

        let cat_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::nn::tensor::channel_cat::ChannelCatForward::<f32>::new(BLOCK_CH),
            &target, true,
        )?)?;
        let cat_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_cat::ChannelCatForward<f32>,
        >(&cat_ptx)?;

        let ow_tiles = W.div_ceil(BLOCK_OW as usize);
        let bn_cfg = |c_ch: usize| CudaLaunchConfig {
            grid: [c_ch as u32, 1, 1], block: [1, 1, 1], cluster: [1, 1, 1],
        };
        let ch_cfg = CudaLaunchConfig {
            grid: [N_SPATIAL as u32, 1, 1],
            block: [BLOCK_CH as u32, 1, 1],
            cluster: [1, 1, 1],
        };

        // cv1 Conv(384→128, 1×1)
        let mut x_buf = device.buffer::<f32>(BATCH * C_IN * H * W)?;
        let mut cv1_cw = device.buffer::<f32>(2 * C * C_IN)?;
        let y_cv1_nchw = device.buffer::<f32>(N_CV1)?;
        x_buf.to_device(&x_host)?;
        cv1_cw.to_device(&cv1_conv_w)?;
        device.launch(&conv1_prog, &CudaLaunchConfig {
            grid: [(BATCH * 2 * C * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            x_buf.as_device_ptr() as *mut f32, cv1_cw.as_device_ptr() as *mut f32,
            y_cv1_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, C_IN as i32, (2 * C) as i32,
            H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut tmp = vec![0f32; N_CV1];
        y_cv1_nchw.to_host(&mut tmp)?;
        let cv1_nc_host = nchw_to_nc(&tmp, BATCH, 2 * C, H, W);

        let mut cv1_nc = device.buffer::<f32>(N_CV1)?;
        let cv1_bn_out = device.buffer::<f32>(N_CV1)?;
        let mut cv1_bnw_buf = device.buffer::<f32>(2 * C)?;
        let mut cv1_bnb_buf = device.buffer::<f32>(2 * C)?;
        let mut cv1_bnrm_buf = device.buffer::<f32>(2 * C)?;
        let mut cv1_bnrv_buf = device.buffer::<f32>(2 * C)?;
        cv1_nc.to_device(&cv1_nc_host)?;
        cv1_bnw_buf.to_device(&cv1_bn_w)?;
        cv1_bnb_buf.to_device(&cv1_bn_b)?;
        cv1_bnrm_buf.to_device(&cv1_bn_rm)?;
        cv1_bnrv_buf.to_device(&cv1_bn_rv)?;
        device.launch(&bn_prog, &bn_cfg(2 * C), (
            cv1_nc.as_device_ptr() as *mut f32, cv1_bn_out.as_device_ptr() as *mut f32,
            cv1_bnw_buf.as_device_ptr() as *mut f32, cv1_bnb_buf.as_device_ptr() as *mut f32,
            cv1_bnrm_buf.as_device_ptr() as *mut f32, cv1_bnrv_buf.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, (2 * C) as i32, BN_EPS,
        ))?;
        let cv1_silu = device.buffer::<f32>(N_CV1)?;
        device.launch(&silu_prog, &testing::launch_config(N_CV1, BLOCK_SILU), (
            cv1_bn_out.as_device_ptr() as *mut f32, cv1_silu.as_device_ptr() as *mut f32,
            N_CV1 as i32,
        ))?;

        // ChannelChunk → [y0, y1]
        let y0_buf = device.buffer::<f32>(N_HALF)?;
        let y1_buf = device.buffer::<f32>(N_HALF)?;
        device.launch(&chunk_prog, &ch_cfg, (
            cv1_silu.as_device_ptr() as *mut f32, y0_buf.as_device_ptr() as *mut f32,
            (2 * C) as i32, C as i32, 0i32,
        ))?;
        device.launch(&chunk_prog, &ch_cfg, (
            cv1_silu.as_device_ptr() as *mut f32, y1_buf.as_device_ptr() as *mut f32,
            (2 * C) as i32, C as i32, C as i32,
        ))?;

        // m0_cv1 Conv(64→32, 3×3)
        let mut y1_host = vec![0f32; N_HALF];
        y1_buf.to_host(&mut y1_host)?;
        let y1_nchw = nc_to_nchw(&y1_host, BATCH, C, H, W);
        let mut y1_nchw_buf = device.buffer::<f32>(N_HALF)?;
        let mut m0cw1 = device.buffer::<f32>(C_INNER * C * 9)?;
        let y_m0cv1_nchw = device.buffer::<f32>(N_M0CV1)?;
        y1_nchw_buf.to_device(&y1_nchw)?;
        m0cw1.to_device(&m0cv1_conv_w)?;
        device.launch(&conv3_prog, &CudaLaunchConfig {
            grid: [(BATCH * C_INNER * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            y1_nchw_buf.as_device_ptr() as *mut f32, m0cw1.as_device_ptr() as *mut f32,
            y_m0cv1_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, C as i32, C_INNER as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut tmp = vec![0f32; N_M0CV1];
        y_m0cv1_nchw.to_host(&mut tmp)?;
        let m0cv1_nc_host = nchw_to_nc(&tmp, BATCH, C_INNER, H, W);

        let mut m0cv1_nc = device.buffer::<f32>(N_M0CV1)?;
        let m0cv1_bn_out = device.buffer::<f32>(N_M0CV1)?;
        let mut m0cv1_bnw_buf = device.buffer::<f32>(C_INNER)?;
        let mut m0cv1_bnb_buf = device.buffer::<f32>(C_INNER)?;
        let mut m0cv1_bnrm_buf = device.buffer::<f32>(C_INNER)?;
        let mut m0cv1_bnrv_buf = device.buffer::<f32>(C_INNER)?;
        m0cv1_nc.to_device(&m0cv1_nc_host)?;
        m0cv1_bnw_buf.to_device(&m0cv1_bn_w)?;
        m0cv1_bnb_buf.to_device(&m0cv1_bn_b)?;
        m0cv1_bnrm_buf.to_device(&m0cv1_bn_rm)?;
        m0cv1_bnrv_buf.to_device(&m0cv1_bn_rv)?;
        device.launch(&bn_prog, &bn_cfg(C_INNER), (
            m0cv1_nc.as_device_ptr() as *mut f32, m0cv1_bn_out.as_device_ptr() as *mut f32,
            m0cv1_bnw_buf.as_device_ptr() as *mut f32, m0cv1_bnb_buf.as_device_ptr() as *mut f32,
            m0cv1_bnrm_buf.as_device_ptr() as *mut f32, m0cv1_bnrv_buf.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, C_INNER as i32, BN_EPS,
        ))?;
        let m0cv1_silu = device.buffer::<f32>(N_M0CV1)?;
        device.launch(&silu_prog, &testing::launch_config(N_M0CV1, BLOCK_SILU), (
            m0cv1_bn_out.as_device_ptr() as *mut f32, m0cv1_silu.as_device_ptr() as *mut f32,
            N_M0CV1 as i32,
        ))?;

        // m0_cv2 Conv(32→64, 3×3)
        let mut m0cv1_silu_host = vec![0f32; N_M0CV1];
        m0cv1_silu.to_host(&mut m0cv1_silu_host)?;
        let m0cv1_silu_nchw = nc_to_nchw(&m0cv1_silu_host, BATCH, C_INNER, H, W);
        let mut m0cv1_silu_nchw_buf = device.buffer::<f32>(N_M0CV1)?;
        let mut m0cw2 = device.buffer::<f32>(C * C_INNER * 9)?;
        let y_m0cv2_nchw = device.buffer::<f32>(N_M0CV2)?;
        m0cv1_silu_nchw_buf.to_device(&m0cv1_silu_nchw)?;
        m0cw2.to_device(&m0cv2_conv_w)?;
        device.launch(&conv3_prog, &CudaLaunchConfig {
            grid: [(BATCH * C * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            m0cv1_silu_nchw_buf.as_device_ptr() as *mut f32, m0cw2.as_device_ptr() as *mut f32,
            y_m0cv2_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, C_INNER as i32, C as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut tmp = vec![0f32; N_M0CV2];
        y_m0cv2_nchw.to_host(&mut tmp)?;
        let m0cv2_nc_host = nchw_to_nc(&tmp, BATCH, C, H, W);

        let mut m0cv2_nc = device.buffer::<f32>(N_M0CV2)?;
        let m0cv2_bn_out = device.buffer::<f32>(N_M0CV2)?;
        let mut m0cv2_bnw_buf = device.buffer::<f32>(C)?;
        let mut m0cv2_bnb_buf = device.buffer::<f32>(C)?;
        let mut m0cv2_bnrm_buf = device.buffer::<f32>(C)?;
        let mut m0cv2_bnrv_buf = device.buffer::<f32>(C)?;
        m0cv2_nc.to_device(&m0cv2_nc_host)?;
        m0cv2_bnw_buf.to_device(&m0cv2_bn_w)?;
        m0cv2_bnb_buf.to_device(&m0cv2_bn_b)?;
        m0cv2_bnrm_buf.to_device(&m0cv2_bn_rm)?;
        m0cv2_bnrv_buf.to_device(&m0cv2_bn_rv)?;
        device.launch(&bn_prog, &bn_cfg(C), (
            m0cv2_nc.as_device_ptr() as *mut f32, m0cv2_bn_out.as_device_ptr() as *mut f32,
            m0cv2_bnw_buf.as_device_ptr() as *mut f32, m0cv2_bnb_buf.as_device_ptr() as *mut f32,
            m0cv2_bnrm_buf.as_device_ptr() as *mut f32, m0cv2_bnrv_buf.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, C as i32, BN_EPS,
        ))?;
        let m0cv2_silu = device.buffer::<f32>(N_M0CV2)?;
        device.launch(&silu_prog, &testing::launch_config(N_M0CV2, BLOCK_SILU), (
            m0cv2_bn_out.as_device_ptr() as *mut f32, m0cv2_silu.as_device_ptr() as *mut f32,
            N_M0CV2 as i32,
        ))?;

        // ChannelCat([y0, y1, m0cv2_silu]) → 192 channels
        let cat_buf = device.buffer::<f32>(N_CAT)?;
        device.launch(&cat_prog, &ch_cfg, (
            y0_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            C as i32, C_CAT as i32, 0i32,
        ))?;
        device.launch(&cat_prog, &ch_cfg, (
            y1_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            C as i32, C_CAT as i32, C as i32,
        ))?;
        device.launch(&cat_prog, &ch_cfg, (
            m0cv2_silu.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            C as i32, C_CAT as i32, (2 * C) as i32,
        ))?;

        // cv2 Conv(192→128, 1×1)
        let mut cat_host = vec![0f32; N_CAT];
        cat_buf.to_host(&mut cat_host)?;
        let cat_nchw = nc_to_nchw(&cat_host, BATCH, C_CAT, H, W);
        let mut cat_nchw_buf = device.buffer::<f32>(N_CAT)?;
        let mut cv2_cw = device.buffer::<f32>(C_OUT * C_CAT)?;
        let y_cv2_nchw = device.buffer::<f32>(N_CV2)?;
        cat_nchw_buf.to_device(&cat_nchw)?;
        cv2_cw.to_device(&cv2_conv_w)?;
        device.launch(&conv1_prog, &CudaLaunchConfig {
            grid: [(BATCH * C_OUT * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            cat_nchw_buf.as_device_ptr() as *mut f32, cv2_cw.as_device_ptr() as *mut f32,
            y_cv2_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, C_CAT as i32, C_OUT as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut tmp = vec![0f32; N_CV2];
        y_cv2_nchw.to_host(&mut tmp)?;
        let cv2_nc_host = nchw_to_nc(&tmp, BATCH, C_OUT, H, W);

        let mut cv2_nc = device.buffer::<f32>(N_CV2)?;
        let cv2_bn_out = device.buffer::<f32>(N_CV2)?;
        let mut cv2_bnw_buf = device.buffer::<f32>(C_OUT)?;
        let mut cv2_bnb_buf = device.buffer::<f32>(C_OUT)?;
        let mut cv2_bnrm_buf = device.buffer::<f32>(C_OUT)?;
        let mut cv2_bnrv_buf = device.buffer::<f32>(C_OUT)?;
        cv2_nc.to_device(&cv2_nc_host)?;
        cv2_bnw_buf.to_device(&cv2_bn_w)?;
        cv2_bnb_buf.to_device(&cv2_bn_b)?;
        cv2_bnrm_buf.to_device(&cv2_bn_rm)?;
        cv2_bnrv_buf.to_device(&cv2_bn_rv)?;
        device.launch(&bn_prog, &bn_cfg(C_OUT), (
            cv2_nc.as_device_ptr() as *mut f32, cv2_bn_out.as_device_ptr() as *mut f32,
            cv2_bnw_buf.as_device_ptr() as *mut f32, cv2_bnb_buf.as_device_ptr() as *mut f32,
            cv2_bnrm_buf.as_device_ptr() as *mut f32, cv2_bnrv_buf.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, C_OUT as i32, BN_EPS,
        ))?;
        let cv2_silu = device.buffer::<f32>(N_CV2)?;
        device.launch(&silu_prog, &testing::launch_config(N_CV2, BLOCK_SILU), (
            cv2_bn_out.as_device_ptr() as *mut f32, cv2_silu.as_device_ptr() as *mut f32,
            N_CV2 as i32,
        ))?;

        let mut y_nc = vec![0f32; N_CV2];
        cv2_silu.to_host(&mut y_nc)?;
        let expected_nc = nchw_to_nc(&expected, BATCH, C_OUT, H, W);
        for i in 0..N_CV2 {
            assert!(
                (y_nc[i] - expected_nc[i]).abs() < TOL,
                "head_sf mismatch at {i}: gpu={} expected={}",
                y_nc[i], expected_nc[i],
            );
        }
        Ok(())
    }
}
