/*
 * Copyright 2026 Teenygrad
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// Grouped and depthwise Conv2dBackwardDx / Conv2dBackwardDw CUDA tests.
//
// Two variants, both with BATCH=2, H=W=4, KH=KW=3, stride=1, pad=1:
//
//   depthwise — G = C_IN = C_OUT = 128, weight [128, 1, 3, 3]
//   g4        — G = 4,  C_IN = 8, C_OUT = 8, weight [8, 2, 3, 3]
//
// Each test validates both backward kernels against PyTorch autograd:
//   BackwardDx: dy [B,C_OUT,H,W] × w [C_OUT,C_IN/G,3,3] → dx [B,C_IN,H,W]
//   BackwardDw: dy [B,C_OUT,H,W] × x [B,C_IN,H,W]       → dw [C_OUT,C_IN/G,3,3]
//
// Both kernels accumulate via atomic_add and require zero-initialised outputs.
//
// Fixtures generated by tests/fixtures/conv_grouped/generate_backward.py.

#[cfg(feature = "cuda")]
mod cuda {
    use dotenv::dotenv;
    use serial_test::serial;
    use teeny_cuda::compiler::{compile_kernel, target::Target};
    use teeny_core::device::{Device, buffer::Buffer};
    use teeny_cuda::{device::CudaLaunchConfig, errors::Result, testing};

    const BATCH: usize = 2;
    const H:     usize = 4;
    const W:     usize = 4;

    const BLOCK_OW: i32 = 4;
    const TOL:      f32 = 1e-4;

    fn load(subdir: &str, name: &str) -> Vec<f32> {
        let path = format!(
            "{}/tests/fixtures/conv_grouped/{}/{}",
            env!("CARGO_MANIFEST_DIR"),
            subdir,
            name
        );
        let bytes = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
        bytes
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect()
    }

    #[allow(clippy::too_many_arguments)]
    fn run_grouped_conv_backward(
        device:      &teeny_cuda::device::CudaDevice,
        target:      &Target,
        x_host:      &[f32],
        w_host:      &[f32],
        dy_host:     &[f32],
        dx_expected: &[f32],
        dw_expected: &[f32],
        batch:       usize,
        c_in:        usize,
        c_out:       usize,
        h:           usize,
        w:           usize,
        g:           i32,
    ) -> Result<()> {
        let n_x   = batch * c_in  * h * w;
        let n_w   = c_out * (c_in / g as usize) * 9;
        let n_out = batch * c_out * h * w;

        assert_eq!(x_host.len(),      n_x,   "x size mismatch");
        assert_eq!(w_host.len(),      n_w,   "w size mismatch");
        assert_eq!(dy_host.len(),     n_out, "dy size mismatch");
        assert_eq!(dx_expected.len(), n_x,   "dx_expected size mismatch");
        assert_eq!(dw_expected.len(), n_w,   "dw_expected size mismatch");

        let ow_tiles = w.div_ceil(BLOCK_OW as usize);
        let launch_cfg = CudaLaunchConfig {
            grid:    [(batch * c_out * h * ow_tiles) as u32, 1, 1],
            block:   [128, 1, 1],
            cluster: [1, 1, 1],
        };

        // Shared buffers for both backward passes.
        let mut dy_buf = device.buffer::<f32>(n_out)?;
        let mut w_buf  = device.buffer::<f32>(n_w)?;
        let mut x_buf  = device.buffer::<f32>(n_x)?;
        dy_buf.to_device(dy_host)?;
        w_buf.to_device(w_host)?;
        x_buf.to_device(x_host)?;

        // ── BackwardDx ────────────────────────────────────────────────────────
        let dx_kernel = teeny_kernels::nn::conv::conv2d::Conv2dBackwardDx::<f32>::new(
            3, 3, 1, 1, 1, 1, g, BLOCK_OW,
        );
        let dx_ptx  = std::fs::read(compile_kernel(&dx_kernel, target, true, false)?)?;
        let dx_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dBackwardDx<f32>,
        >(&dx_ptx)?;

        let mut dx_buf = device.buffer::<f32>(n_x)?;
        let zeros_x = vec![0.0f32; n_x];
        dx_buf.to_device(&zeros_x)?;

        device.launch(&dx_prog, &launch_cfg, (
            dy_buf.as_device_ptr() as *mut f32,
            w_buf.as_device_ptr() as *mut f32,
            dx_buf.as_device_ptr() as *mut f32,
            batch as i32, c_in as i32, c_out as i32,
            h as i32, w as i32, h as i32, w as i32,
        ))?;

        let mut dx_gpu = vec![0.0f32; n_x];
        dx_buf.to_host(&mut dx_gpu)?;
        for i in 0..n_x {
            assert!(
                (dx_gpu[i] - dx_expected[i]).abs() < TOL,
                "BackwardDx g={g} mismatch at {i}: got={} expected={}",
                dx_gpu[i], dx_expected[i],
            );
        }

        // ── BackwardDw ────────────────────────────────────────────────────────
        let dw_kernel = teeny_kernels::nn::conv::conv2d::Conv2dBackwardDw::<f32>::new(
            3, 3, 1, 1, 1, 1, g, BLOCK_OW,
        );
        let dw_ptx  = std::fs::read(compile_kernel(&dw_kernel, target, true, false)?)?;
        let dw_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dBackwardDw<f32>,
        >(&dw_ptx)?;

        let mut dw_buf = device.buffer::<f32>(n_w)?;
        let zeros_w = vec![0.0f32; n_w];
        dw_buf.to_device(&zeros_w)?;

        device.launch(&dw_prog, &launch_cfg, (
            dy_buf.as_device_ptr() as *mut f32,
            x_buf.as_device_ptr() as *mut f32,
            dw_buf.as_device_ptr() as *mut f32,
            batch as i32, c_in as i32, c_out as i32,
            h as i32, w as i32, h as i32, w as i32,
        ))?;

        let mut dw_gpu = vec![0.0f32; n_w];
        dw_buf.to_host(&mut dw_gpu)?;
        for i in 0..n_w {
            assert!(
                (dw_gpu[i] - dw_expected[i]).abs() < TOL,
                "BackwardDw g={g} mismatch at {i}: got={} expected={}",
                dw_gpu[i], dw_expected[i],
            );
        }

        Ok(())
    }

    // ── Depthwise (G = C_IN = C_OUT = 128) ───────────────────────────────────────

    #[test]
    #[serial]
    fn test_conv2d_depthwise_backward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        run_grouped_conv_backward(
            &env.device,
            &Target::new(env.capability),
            &load("depthwise", "x.bin"),
            &load("depthwise", "conv_w.bin"),
            &load("depthwise", "dy.bin"),
            &load("depthwise", "dx_expected.bin"),
            &load("depthwise", "dw_expected.bin"),
            BATCH, 128, 128, H, W,
            128,
        )
    }

    // ── Grouped G=4 (C_IN = C_OUT = 8, 2 channels per group) ────────────────────

    #[test]
    #[serial]
    fn test_conv2d_grouped_g4_backward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        run_grouped_conv_backward(
            &env.device,
            &Target::new(env.capability),
            &load("g4", "x.bin"),
            &load("g4", "conv_w.bin"),
            &load("g4", "dy.bin"),
            &load("g4", "dx_expected.bin"),
            &load("g4", "dw_expected.bin"),
            BATCH, 8, 8, H, W,
            4,
        )
    }
}
