/*
 * SpinorML Ltd 🚀 AGPL-3.0 License - https://spinorml.com/license
 */

// Grouped and depthwise Conv2dForward CUDA integration tests.
//
// Two variants, both with BATCH=2, H=4, W=4, KH=KW=3, stride=1, pad=1:
//
//   depthwise — groups = C_IN = C_OUT = 128
//               weight layout [128, 1, 3, 3]   (one filter per channel)
//
//   g4        — groups = 4, C_IN = 8, C_OUT = 8
//               weight layout [8, 2, 3, 3]     (two input channels per group)
//
// These tests exercise the groups (G) const-generic added to Conv2dForward
// and verify the weight-index formula `(c_out * (C_IN/G) + c_in_local) * ...`
// against PyTorch nn.Conv2d(groups=G) reference outputs.
//
// Fixtures generated by tests/fixtures/conv_grouped/generate.py.

#[cfg(feature = "cuda")]
mod cuda {
    use dotenv::dotenv;
    use serial_test::serial;
    use teeny_compiler::compiler::{driver::cuda::compile_kernel, target::cuda::Target};
    use teeny_core::device::{Device, buffer::Buffer};
    use teeny_cuda::{device::CudaLaunchConfig, errors::Result, testing};

    const BATCH: usize = 2;
    const H:     usize = 4;
    const W:     usize = 4;

    const BLOCK_OW: i32 = 4;
    const TOL:      f32 = 1e-5;

    fn load(subdir: &str, name: &str) -> Vec<f32> {
        let path = format!(
            "{}/tests/fixtures/conv_grouped/{}/{}",
            env!("CARGO_MANIFEST_DIR"),
            subdir,
            name
        );
        let bytes = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
        bytes
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect()
    }

    #[allow(clippy::too_many_arguments)]
    fn run_grouped_conv(
        device:   &teeny_cuda::device::CudaDevice,
        target:   &Target,
        x_host:   &[f32],
        w_host:   &[f32],
        expected: &[f32],
        batch:    usize,
        c_in:     usize,
        c_out:    usize,
        h:        usize,
        w:        usize,
        g:        i32,
    ) -> Result<()> {
        // Compile the grouped conv kernel (G baked in as const generic).
        let kernel = teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(
            3, 3, 1, 1, 1, 1, g, BLOCK_OW,
        );
        let ptx  = std::fs::read(compile_kernel(&kernel, target, true)?)?;
        let prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&ptx)?;

        let n_x   = batch * c_in  * h * w;
        let n_w   = c_out * (c_in / g as usize) * 9;
        let n_out = batch * c_out * h * w;

        assert_eq!(x_host.len(),   n_x,  "x size mismatch");
        assert_eq!(w_host.len(),   n_w,  "weight size mismatch");
        assert_eq!(expected.len(), n_out, "expected size mismatch");

        let mut x_buf = device.buffer::<f32>(n_x)?;
        let mut w_buf = device.buffer::<f32>(n_w)?;
        let y_buf     = device.buffer::<f32>(n_out)?;

        x_buf.to_device(x_host)?;
        w_buf.to_device(w_host)?;

        let ow_tiles = w.div_ceil(BLOCK_OW as usize);
        device.launch(&prog, &CudaLaunchConfig {
            grid:    [(batch * c_out * h * ow_tiles) as u32, 1, 1],
            block:   [128, 1, 1],
            cluster: [1, 1, 1],
        }, (
            x_buf.as_device_ptr() as *mut f32,
            w_buf.as_device_ptr() as *mut f32,
            y_buf.as_device_ptr() as *mut f32,
            batch as i32, c_in as i32, c_out as i32,
            h as i32, w as i32, h as i32, w as i32,
        ))?;

        let mut y_host = vec![0.0f32; n_out];
        y_buf.to_host(&mut y_host)?;

        for i in 0..n_out {
            assert!(
                (y_host[i] - expected[i]).abs() < TOL,
                "grouped conv g={g} mismatch at element {i}: \
                 got={} expected={}",
                y_host[i], expected[i],
            );
        }
        Ok(())
    }

    // ── Depthwise (groups = C_IN = C_OUT = 128) ──────────────────────────────────

    #[test]
    #[serial]
    fn test_conv2d_depthwise_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        run_grouped_conv(
            &env.device,
            &Target::new(env.capability),
            &load("depthwise", "x.bin"),
            &load("depthwise", "conv_w.bin"),
            &load("depthwise", "expected_output.bin"),
            BATCH, 128, 128, H, W,
            128,   // G = C_IN = C_OUT  (pure depthwise)
        )
    }

    // ── Grouped, G=4 (C_IN=8, C_OUT=8, 2 channels per group) ────────────────────

    #[test]
    #[serial]
    fn test_conv2d_grouped_g4_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        run_grouped_conv(
            &env.device,
            &Target::new(env.capability),
            &load("g4", "x.bin"),
            &load("g4", "conv_w.bin"),
            &load("g4", "expected_output.bin"),
            BATCH, 8, 8, H, W,
            4,     // G=4, c_in_per_group=2
        )
    }
}
