/*
 * SpinorML Ltd 🚀 AGPL-3.0 License - https://spinorml.com/license
 */

// C2PSA block end-to-end CUDA forward-pass test.
//
// Parameters: C2PSA(c1=256, c2=256, n=1, e=0.5)
//
//   c         = int(256 * 0.5) = 128   hidden channels
//   num_heads = c // 64        = 2
//   head_dim  = c // num_heads = 64
//   key_dim   = int(64 * 0.5)  = 32
//   qkv_h     = c + key_dim * num_heads * 2 = 256
//
//   cv1:   Conv(256→256, 1×1) → BN(256) → SiLU
//   split: a=(B,128,H,W)  b=(B,128,H,W)
//
//   PSABlock on b:
//     Attention:
//       qkv:  Conv(128→256, 1×1) → BN(256)                  [no SiLU]
//       Q=(B,2,32,N)  K=(B,2,32,N)  V=(B,2,64,N)
//       attn  = softmax(Q.T @ K * scale)          ← host-side
//       out   = (V @ attn.T).view(B,128,H,W)      ← host-side
//             + pe(V_spatial)
//       pe:   depthwise Conv(128→128, 3×3, g=128) → BN(128) [no SiLU, CUDA G=128]
//       proj: Conv(128→128, 1×1) → BN(128)                  [no SiLU]
//       b     = b + proj_out
//     FFN:
//       ffn0: Conv(128→256, 1×1) → BN(256) → SiLU
//       ffn1: Conv(256→128, 1×1) → BN(128)                  [no SiLU]
//       b     = b + ffn1_out
//
//   cat(a, b) → (B, 256, H, W)
//   cv2:   Conv(256→256, 1×1) → BN(256) → SiLU
//
// Layout conventions:
//   Conv kernel:                    NCHW input/output
//   BN / SiLU / Chunk / Cat / VAdd: NC layout = (B*H*W, C) row-major
//   Host nchw_to_nc / nc_to_nchw bridge the two stages.
//
// Attention matmul is computed host-side (no batched-matmul CUDA kernel available yet).
// The pe depthwise convolution uses the grouped Conv2dForward kernel with G=C=128.
//
// Fixtures generated by tests/fixtures/c2psa_yolo26/generate.py using
// ultralytics C2PSA in eval() mode as the reference.

#[cfg(feature = "cuda")]
mod cuda {
    use dotenv::dotenv;
    use serial_test::serial;
    use teeny_compiler::compiler::{driver::cuda::compile_kernel, target::cuda::Target};
    use teeny_core::device::{Device, buffer::Buffer};
    use teeny_cuda::{device::CudaLaunchConfig, errors::Result, testing};

    // ── Dimensions ────────────────────────────────────────────────────────────────
    const BATCH:     usize = 2;
    const C1:        usize = 256;  // c_in = c_out
    const C:         usize = 128;  // C1 * e = 256 * 0.5
    const H:         usize = 4;
    const W:         usize = 4;

    const NUM_HEADS: usize = 2;    // C / 64
    const HEAD_DIM:  usize = 64;   // C / NUM_HEADS
    const KEY_DIM:   usize = 32;   // int(HEAD_DIM * 0.5)
    const QKV_H:     usize = 256;  // C + KEY_DIM * NUM_HEADS * 2  =  128 + 128
    const HEAD_SPAN: usize = 2 * KEY_DIM + HEAD_DIM;  // 128 = QKV_H / NUM_HEADS
    const SCALE:     f32   = 0.176_776_7_f32;          // 1 / sqrt(KEY_DIM=32)
    const N:         usize = H * W;                    // 16 spatial positions
    const N_SPATIAL: usize = BATCH * N;                // 32

    // ── Buffer element counts ─────────────────────────────────────────────────────
    const BUF_X:    usize = N_SPATIAL * C1;       // 8192
    const BUF_CV1:  usize = N_SPATIAL * C1;       // 8192  (cv1 out, 256 ch)
    const BUF_HALF: usize = N_SPATIAL * C;        // 4096  (a or b, 128 ch)
    const BUF_QKV:  usize = N_SPATIAL * QKV_H;   // 8192  (qkv out, 256 ch)
    const BUF_FFN0: usize = N_SPATIAL * 2 * C;   // 8192  (ffn0 out, 256 ch)
    const BUF_CAT:  usize = N_SPATIAL * C1;       // 8192  (cat out, 256 ch)

    // ── Kernel tuning ─────────────────────────────────────────────────────────────
    const BLOCK_OW:   i32 = 4;
    const BLOCK_BN:   i32 = 128;
    const BLOCK_SILU: i32 = 128;
    const BLOCK_CH:   i32 = 128;
    const BLOCK_VADD: i32 = 128;
    const BN_EPS:     f32 = 1e-5;

    // ── Fixture loader ────────────────────────────────────────────────────────────

    fn load_fixture(name: &str) -> Vec<f32> {
        let path = format!(
            "{}/tests/fixtures/c2psa_yolo26/{}",
            env!("CARGO_MANIFEST_DIR"),
            name
        );
        let bytes = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
        bytes
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect()
    }

    // ── Layout converters ─────────────────────────────────────────────────────────

    fn nchw_to_nc(src: &[f32], b: usize, c: usize, h: usize, w: usize) -> Vec<f32> {
        let mut out = vec![0.0f32; b * h * w * c];
        for bi in 0..b {
            for ci in 0..c {
                for hi in 0..h {
                    for wi in 0..w {
                        let ni = bi * h * w + hi * w + wi;
                        out[ni * c + ci] = src[bi * c * h * w + ci * h * w + hi * w + wi];
                    }
                }
            }
        }
        out
    }

    fn nc_to_nchw(src: &[f32], b: usize, c: usize, h: usize, w: usize) -> Vec<f32> {
        let mut out = vec![0.0f32; b * c * h * w];
        for bi in 0..b {
            for ci in 0..c {
                for hi in 0..h {
                    for wi in 0..w {
                        let ni = bi * h * w + hi * w + wi;
                        out[bi * c * h * w + ci * h * w + hi * w + wi] = src[ni * c + ci];
                    }
                }
            }
        }
        out
    }

    // ── Host-side attention ───────────────────────────────────────────────────────

    // Compute self-attention on the BN-normalised QKV projection (NCHW).
    //
    // Returns:
    //   attn_out_nchw — (B, C, H, W) attention output
    //   v_nchw        — (B, C, H, W) value tensor reshaped for pe
    //
    // Memory layout of qkv_nchw: (B, QKV_H, H, W) row-major.
    // Channel layout per head h: [q: KEY_DIM | k: KEY_DIM | v: HEAD_DIM]
    //   channel index = h * HEAD_SPAN + offset
    fn compute_attention(qkv_nchw: &[f32]) -> (Vec<f32>, Vec<f32>) {
        let n = N;
        let c = NUM_HEADS * HEAD_DIM;

        let mut attn_out = vec![0.0f32; BATCH * c * n];
        let mut v_nchw   = vec![0.0f32; BATCH * c * n];

        for bi in 0..BATCH {
            for hi in 0..NUM_HEADS {
                let q_ch_base = hi * HEAD_SPAN;              // start of Q channels
                let k_ch_base = q_ch_base + KEY_DIM;         // start of K channels
                let v_ch_base = q_ch_base + 2 * KEY_DIM;     // start of V channels

                // Attention scores[qi, ki] = (sum_d q[d,qi] * k[d,ki]) * scale
                let mut scores = vec![0.0f32; n * n];
                for qi in 0..n {
                    for ki in 0..n {
                        let mut dot = 0.0f32;
                        for d in 0..KEY_DIM {
                            let q_val = qkv_nchw[bi * QKV_H * n + (q_ch_base + d) * n + qi];
                            let k_val = qkv_nchw[bi * QKV_H * n + (k_ch_base + d) * n + ki];
                            dot += q_val * k_val;
                        }
                        scores[qi * n + ki] = dot * SCALE;
                    }
                }

                // Row-wise softmax (over ki)
                for qi in 0..n {
                    let row = &mut scores[qi * n..(qi + 1) * n];
                    let max = row.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
                    let sum: f32 = row.iter().map(|&x| (x - max).exp()).sum();
                    for x in row.iter_mut() {
                        *x = (*x - max).exp() / sum;
                    }
                }

                // out[d, qi] = sum_ki  v[d, ki] * attn[qi, ki]
                for d in 0..HEAD_DIM {
                    let v_ch  = v_ch_base + d;
                    let out_ch = hi * HEAD_DIM + d;
                    for qi in 0..n {
                        let mut acc = 0.0f32;
                        for ki in 0..n {
                            let v_val = qkv_nchw[bi * QKV_H * n + v_ch * n + ki];
                            acc += v_val * scores[qi * n + ki];
                        }
                        attn_out[bi * c * n + out_ch * n + qi] = acc;
                    }

                    // Build v_nchw: v.reshape(B, C, H, W) in contiguous order.
                    // v[b, h, d, n] → v_nchw[b, h*HEAD_DIM+d, n]
                    for ni in 0..n {
                        v_nchw[bi * c * n + out_ch * n + ni] =
                            qkv_nchw[bi * QKV_H * n + v_ch * n + ni];
                    }
                }
            }
        }

        (attn_out, v_nchw)
    }

    // ── Test ──────────────────────────────────────────────────────────────────────

    #[test]
    #[serial]
    fn test_c2psa_yolo26_forward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;
        let target = Target::new(env.capability);

        // ── Load fixtures ─────────────────────────────────────────────────────────
        let x_host = load_fixture("x.bin");

        let cv1_conv_w = load_fixture("cv1_conv_w.bin");
        let cv1_bn_w   = load_fixture("cv1_bn_w.bin");
        let cv1_bn_b   = load_fixture("cv1_bn_b.bin");
        let cv1_bn_rm  = load_fixture("cv1_bn_rm.bin");
        let cv1_bn_rv  = load_fixture("cv1_bn_rv.bin");

        let qkv_conv_w = load_fixture("m0_attn_qkv_conv_w.bin");
        let qkv_bn_w   = load_fixture("m0_attn_qkv_bn_w.bin");
        let qkv_bn_b   = load_fixture("m0_attn_qkv_bn_b.bin");
        let qkv_bn_rm  = load_fixture("m0_attn_qkv_bn_rm.bin");
        let qkv_bn_rv  = load_fixture("m0_attn_qkv_bn_rv.bin");

        let pe_conv_w = load_fixture("m0_attn_pe_conv_w.bin");
        let pe_bn_w   = load_fixture("m0_attn_pe_bn_w.bin");
        let pe_bn_b   = load_fixture("m0_attn_pe_bn_b.bin");
        let pe_bn_rm  = load_fixture("m0_attn_pe_bn_rm.bin");
        let pe_bn_rv  = load_fixture("m0_attn_pe_bn_rv.bin");

        let proj_conv_w = load_fixture("m0_attn_proj_conv_w.bin");
        let proj_bn_w   = load_fixture("m0_attn_proj_bn_w.bin");
        let proj_bn_b   = load_fixture("m0_attn_proj_bn_b.bin");
        let proj_bn_rm  = load_fixture("m0_attn_proj_bn_rm.bin");
        let proj_bn_rv  = load_fixture("m0_attn_proj_bn_rv.bin");

        let ffn0_conv_w = load_fixture("m0_ffn0_conv_w.bin");
        let ffn0_bn_w   = load_fixture("m0_ffn0_bn_w.bin");
        let ffn0_bn_b   = load_fixture("m0_ffn0_bn_b.bin");
        let ffn0_bn_rm  = load_fixture("m0_ffn0_bn_rm.bin");
        let ffn0_bn_rv  = load_fixture("m0_ffn0_bn_rv.bin");

        let ffn1_conv_w = load_fixture("m0_ffn1_conv_w.bin");
        let ffn1_bn_w   = load_fixture("m0_ffn1_bn_w.bin");
        let ffn1_bn_b   = load_fixture("m0_ffn1_bn_b.bin");
        let ffn1_bn_rm  = load_fixture("m0_ffn1_bn_rm.bin");
        let ffn1_bn_rv  = load_fixture("m0_ffn1_bn_rv.bin");

        let cv2_conv_w = load_fixture("cv2_conv_w.bin");
        let cv2_bn_w   = load_fixture("cv2_bn_w.bin");
        let cv2_bn_b   = load_fixture("cv2_bn_b.bin");
        let cv2_bn_rm  = load_fixture("cv2_bn_rm.bin");
        let cv2_bn_rv  = load_fixture("cv2_bn_rv.bin");

        let expected = load_fixture("expected_output.bin");

        // Sanity-check shapes
        assert_eq!(x_host.len(),      BUF_X);
        assert_eq!(cv1_conv_w.len(),  C1 * C1);           // [256,256,1,1]
        assert_eq!(qkv_conv_w.len(),  QKV_H * C);         // [256,128,1,1]
        assert_eq!(pe_conv_w.len(),   C * 9);              // [128,1,3,3]
        assert_eq!(proj_conv_w.len(), C * C);              // [128,128,1,1]
        assert_eq!(ffn0_conv_w.len(), 2 * C * C);         // [256,128,1,1]
        assert_eq!(ffn1_conv_w.len(), C * 2 * C);         // [128,256,1,1]
        assert_eq!(cv2_conv_w.len(),  C1 * C1);           // [256,256,1,1]
        assert_eq!(expected.len(),    BUF_X);

        // ── Compile kernels ───────────────────────────────────────────────────────

        // Conv 1×1 (cv1, qkv, proj, ffn0, ffn1, cv2 — all groups=1)
        let conv1_kernel = teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(
            1, 1, 1, 1, 0, 0, 1, BLOCK_OW,
        );
        let conv1_ptx = std::fs::read(compile_kernel(&conv1_kernel, &target, true)?)?;
        let conv1_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&conv1_ptx)?;

        // Depthwise 3×3 conv (pe layer: G = C_IN = C_OUT = 128)
        let conv_dw_kernel = teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(
            3, 3, 1, 1, 1, 1, C as i32, BLOCK_OW,
        );
        let conv_dw_ptx = std::fs::read(compile_kernel(&conv_dw_kernel, &target, true)?)?;
        let conv_dw_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&conv_dw_ptx)?;

        // BatchNorm inference
        let bn_kernel = teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference::<f32>::new(BLOCK_BN);
        let bn_ptx = std::fs::read(compile_kernel(&bn_kernel, &target, true)?)?;
        let bn_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference<f32>,
        >(&bn_ptx)?;

        // SiLU
        let silu_kernel = teeny_kernels::nn::activation::sigmoid::SiluForward::new(BLOCK_SILU);
        let silu_ptx = std::fs::read(compile_kernel(&silu_kernel, &target, true)?)?;
        let silu_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::activation::sigmoid::SiluForward,
        >(&silu_ptx)?;

        // ChannelChunk
        let chunk_kernel =
            teeny_kernels::nn::tensor::channel_chunk::ChannelChunkForward::<f32>::new(BLOCK_CH);
        let chunk_ptx = std::fs::read(compile_kernel(&chunk_kernel, &target, true)?)?;
        let chunk_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_chunk::ChannelChunkForward<f32>,
        >(&chunk_ptx)?;

        // ChannelCat
        let cat_kernel =
            teeny_kernels::nn::tensor::channel_cat::ChannelCatForward::<f32>::new(BLOCK_CH);
        let cat_ptx = std::fs::read(compile_kernel(&cat_kernel, &target, true)?)?;
        let cat_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_cat::ChannelCatForward<f32>,
        >(&cat_ptx)?;

        // VectorAdd (residual shortcut adds)
        let vadd_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::math::add::VectorAdd::<f32>::new(BLOCK_VADD),
            &target, true,
        )?)?;
        let vadd_prog = testing::load_program_from_ptx::<
            teeny_kernels::math::add::VectorAdd<f32>,
        >(&vadd_ptx)?;

        // ── Reusable launch helpers ───────────────────────────────────────────────
        let ow_tiles = W.div_ceil(BLOCK_OW as usize);

        // Conv 1×1 launch config: one CTA per (b, c_out, oh, ow_tile)
        let conv1_cfg = |b_batch: usize, c_out: usize| CudaLaunchConfig {
            grid:  [(b_batch * c_out * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1],
            cluster: [1, 1, 1],
        };

        // BN: one CTA per channel, loops over N_SPATIAL internally
        let bn_cfg = |c_ch: usize| CudaLaunchConfig {
            grid: [c_ch as u32, 1, 1], block: [1, 1, 1], cluster: [1, 1, 1],
        };

        // ChannelChunk / ChannelCat: one CTA per spatial position
        let ch_cfg = CudaLaunchConfig {
            grid:  [N_SPATIAL as u32, 1, 1],
            block: [BLOCK_CH as u32, 1, 1],
            cluster: [1, 1, 1],
        };

        // Helper: run BN inference (NC in → NC out), no SiLU
        macro_rules! run_bn {
            ($in_nc_buf:expr, $c_ch:expr, $w_host:expr, $b_host:expr, $rm:expr, $rv:expr) => {{
                let out_buf = device.buffer::<f32>(N_SPATIAL * $c_ch)?;
                let mut w_buf  = device.buffer::<f32>($c_ch)?;
                let mut b_buf  = device.buffer::<f32>($c_ch)?;
                let mut rm_buf = device.buffer::<f32>($c_ch)?;
                let mut rv_buf = device.buffer::<f32>($c_ch)?;
                w_buf.to_device(&$w_host)?;
                b_buf.to_device(&$b_host)?;
                rm_buf.to_device(&$rm)?;
                rv_buf.to_device(&$rv)?;
                device.launch(&bn_prog, &bn_cfg($c_ch), (
                    $in_nc_buf.as_device_ptr() as *mut f32,
                    out_buf.as_device_ptr() as *mut f32,
                    w_buf.as_device_ptr() as *mut f32,
                    b_buf.as_device_ptr() as *mut f32,
                    rm_buf.as_device_ptr() as *mut f32,
                    rv_buf.as_device_ptr() as *mut f32,
                    N_SPATIAL as i32, $c_ch as i32, BN_EPS,
                ))?;
                out_buf
            }};
        }

        // Helper: NC host → device, Conv 1×1 (NCHW → NCHW), result back as NC host
        macro_rules! conv1_nc_to_nc_host {
            ($nc_host:expr, $c_in:expr, $c_out:expr, $w_host:expr) => {{
                let nchw_in  = nc_to_nchw(&$nc_host, BATCH, $c_in, H, W);
                let mut x_buf = device.buffer::<f32>(BATCH * $c_in * H * W)?;
                let mut w_buf = device.buffer::<f32>($c_out * $c_in)?;
                let y_buf     = device.buffer::<f32>(BATCH * $c_out * H * W)?;
                x_buf.to_device(&nchw_in)?;
                w_buf.to_device(&$w_host)?;
                device.launch(&conv1_prog, &conv1_cfg(BATCH, $c_out), (
                    x_buf.as_device_ptr() as *mut f32,
                    w_buf.as_device_ptr() as *mut f32,
                    y_buf.as_device_ptr() as *mut f32,
                    BATCH as i32, $c_in as i32, $c_out as i32,
                    H as i32, W as i32, H as i32, W as i32,
                ))?;
                let mut tmp = vec![0.0f32; BATCH * $c_out * H * W];
                y_buf.to_host(&mut tmp)?;
                nchw_to_nc(&tmp, BATCH, $c_out, H, W)
            }};
        }

        // ── Stage 1: cv1 Conv(256→256, 1×1) → BN(256) → SiLU ────────────────────
        let mut x_buf     = device.buffer::<f32>(BUF_X)?;
        let mut cv1_w_buf = device.buffer::<f32>(C1 * C1)?;
        let y_cv1_nchw    = device.buffer::<f32>(BUF_CV1)?;

        x_buf.to_device(&x_host)?;
        cv1_w_buf.to_device(&cv1_conv_w)?;

        device.launch(&conv1_prog, &conv1_cfg(BATCH, C1), (
            x_buf.as_device_ptr() as *mut f32,
            cv1_w_buf.as_device_ptr() as *mut f32,
            y_cv1_nchw.as_device_ptr() as *mut f32,
            BATCH as i32, C1 as i32, C1 as i32,
            H as i32, W as i32, H as i32, W as i32,
        ))?;

        let mut tmp = vec![0.0f32; BUF_CV1];
        y_cv1_nchw.to_host(&mut tmp)?;
        let cv1_nc_host = nchw_to_nc(&tmp, BATCH, C1, H, W);

        let mut cv1_nc_buf = device.buffer::<f32>(BUF_CV1)?;
        cv1_nc_buf.to_device(&cv1_nc_host)?;

        let cv1_bn_buf = run_bn!(cv1_nc_buf, C1, cv1_bn_w, cv1_bn_b, cv1_bn_rm, cv1_bn_rv);

        let cv1_silu = device.buffer::<f32>(BUF_CV1)?;
        device.launch(&silu_prog, &testing::launch_config(BUF_CV1, BLOCK_SILU), (
            cv1_bn_buf.as_device_ptr() as *mut f32,
            cv1_silu.as_device_ptr() as *mut f32,
            BUF_CV1 as i32,
        ))?;

        // ── Stage 2: ChannelChunk → a (ch 0..128)  b (ch 128..256) ───────────────
        let a_buf = device.buffer::<f32>(BUF_HALF)?;
        let b_buf = device.buffer::<f32>(BUF_HALF)?;

        device.launch(&chunk_prog, &ch_cfg, (
            cv1_silu.as_device_ptr() as *mut f32,
            a_buf.as_device_ptr() as *mut f32,
            C1 as i32, C as i32, 0i32,
        ))?;
        device.launch(&chunk_prog, &ch_cfg, (
            cv1_silu.as_device_ptr() as *mut f32,
            b_buf.as_device_ptr() as *mut f32,
            C1 as i32, C as i32, C as i32,
        ))?;

        // ── Stage 3a: qkv Conv(128→256, 1×1) → BN(256) [no SiLU] ────────────────
        let mut b_nc_host = vec![0.0f32; BUF_HALF];
        b_buf.to_host(&mut b_nc_host)?;

        let qkv_nc_host = conv1_nc_to_nc_host!(b_nc_host, C, QKV_H, qkv_conv_w);

        let mut qkv_nc_buf = device.buffer::<f32>(BUF_QKV)?;
        qkv_nc_buf.to_device(&qkv_nc_host)?;

        let qkv_bn_buf = run_bn!(qkv_nc_buf, QKV_H, qkv_bn_w, qkv_bn_b, qkv_bn_rm, qkv_bn_rv);

        // ── Stage 3b: attention (host-side matmul) ────────────────────────────────
        // qkv_bn output is NC (N_SPATIAL, QKV_H); convert to NCHW for indexing.
        let mut qkv_bn_host = vec![0.0f32; BUF_QKV];
        qkv_bn_buf.to_host(&mut qkv_bn_host)?;
        let qkv_nchw_host = nc_to_nchw(&qkv_bn_host, BATCH, QKV_H, H, W);

        // (attn_out_nchw, v_nchw) — both (B, C, H, W) in flat NCHW (C=128)
        let (attn_out_nchw, v_nchw) = compute_attention(&qkv_nchw_host);

        // ── Stage 3c: pe depthwise Conv(128→128, 3×3, G=128) + BN(128) [no SiLU] ──
        // v_nchw is (B, C, H, W) produced by the host-side attention step.
        let mut pe_x_buf = device.buffer::<f32>(BUF_HALF)?;
        let mut pe_w_buf = device.buffer::<f32>(C * 9)?;
        let pe_y_buf     = device.buffer::<f32>(BUF_HALF)?;

        pe_x_buf.to_device(&v_nchw)?;
        pe_w_buf.to_device(&pe_conv_w)?;

        device.launch(&conv_dw_prog, &CudaLaunchConfig {
            grid:  [(BATCH * C * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1],
            cluster: [1, 1, 1],
        }, (
            pe_x_buf.as_device_ptr() as *mut f32,
            pe_w_buf.as_device_ptr() as *mut f32,
            pe_y_buf.as_device_ptr() as *mut f32,
            BATCH as i32, C as i32, C as i32,
            H as i32, W as i32, H as i32, W as i32,
        ))?;

        let mut pe_nchw_host = vec![0.0f32; BUF_HALF];
        pe_y_buf.to_host(&mut pe_nchw_host)?;
        let pe_conv_nc = nchw_to_nc(&pe_nchw_host, BATCH, C, H, W);
        let mut pe_nc_buf = device.buffer::<f32>(BUF_HALF)?;
        pe_nc_buf.to_device(&pe_conv_nc)?;

        let pe_bn_buf = run_bn!(pe_nc_buf, C, pe_bn_w, pe_bn_b, pe_bn_rm, pe_bn_rv);

        // ── Stage 3d: VectorAdd(attn_out, pe_bn) → x_attn ────────────────────────
        let attn_out_nc = nchw_to_nc(&attn_out_nchw, BATCH, C, H, W);
        let mut attn_out_nc_buf = device.buffer::<f32>(BUF_HALF)?;
        attn_out_nc_buf.to_device(&attn_out_nc)?;

        let x_attn_buf = device.buffer::<f32>(BUF_HALF)?;
        device.launch(&vadd_prog, &testing::launch_config(BUF_HALF, BLOCK_VADD), (
            attn_out_nc_buf.as_device_ptr() as *mut f32,
            pe_bn_buf.as_device_ptr() as *mut f32,
            x_attn_buf.as_device_ptr() as *mut f32,
            BUF_HALF as i32,
        ))?;

        // ── Stage 3e: proj Conv(128→128, 1×1) → BN(128) [no SiLU] ───────────────
        let mut x_attn_host = vec![0.0f32; BUF_HALF];
        x_attn_buf.to_host(&mut x_attn_host)?;

        let proj_nc_host = conv1_nc_to_nc_host!(x_attn_host, C, C, proj_conv_w);

        let mut proj_nc_buf = device.buffer::<f32>(BUF_HALF)?;
        proj_nc_buf.to_device(&proj_nc_host)?;

        let proj_bn_buf = run_bn!(proj_nc_buf, C, proj_bn_w, proj_bn_b, proj_bn_rm, proj_bn_rv);

        // ── Stage 3f: b = b + proj_out (PSA attention shortcut) ──────────────────
        let b_after_attn_buf = device.buffer::<f32>(BUF_HALF)?;
        device.launch(&vadd_prog, &testing::launch_config(BUF_HALF, BLOCK_VADD), (
            b_buf.as_device_ptr() as *mut f32,
            proj_bn_buf.as_device_ptr() as *mut f32,
            b_after_attn_buf.as_device_ptr() as *mut f32,
            BUF_HALF as i32,
        ))?;

        // ── Stage 4a: ffn0 Conv(128→256, 1×1) → BN(256) → SiLU ─────────────────
        let mut b_attn_nc_host = vec![0.0f32; BUF_HALF];
        b_after_attn_buf.to_host(&mut b_attn_nc_host)?;

        let ffn0_nc_host = conv1_nc_to_nc_host!(b_attn_nc_host, C, 2 * C, ffn0_conv_w);

        let mut ffn0_nc_buf = device.buffer::<f32>(BUF_FFN0)?;
        ffn0_nc_buf.to_device(&ffn0_nc_host)?;

        let ffn0_bn_buf = run_bn!(ffn0_nc_buf, 2 * C, ffn0_bn_w, ffn0_bn_b, ffn0_bn_rm, ffn0_bn_rv);

        let ffn0_silu_buf = device.buffer::<f32>(BUF_FFN0)?;
        device.launch(&silu_prog, &testing::launch_config(BUF_FFN0, BLOCK_SILU), (
            ffn0_bn_buf.as_device_ptr() as *mut f32,
            ffn0_silu_buf.as_device_ptr() as *mut f32,
            BUF_FFN0 as i32,
        ))?;

        // ── Stage 4b: ffn1 Conv(256→128, 1×1) → BN(128) [no SiLU] ──────────────
        let mut ffn0_silu_host = vec![0.0f32; BUF_FFN0];
        ffn0_silu_buf.to_host(&mut ffn0_silu_host)?;

        let ffn1_nc_host = conv1_nc_to_nc_host!(ffn0_silu_host, 2 * C, C, ffn1_conv_w);

        let mut ffn1_nc_buf = device.buffer::<f32>(BUF_HALF)?;
        ffn1_nc_buf.to_device(&ffn1_nc_host)?;

        let ffn1_bn_buf = run_bn!(ffn1_nc_buf, C, ffn1_bn_w, ffn1_bn_b, ffn1_bn_rm, ffn1_bn_rv);

        // ── Stage 4c: b = b + ffn1_out (PSA FFN shortcut) ───────────────────────
        let b_final_buf = device.buffer::<f32>(BUF_HALF)?;
        device.launch(&vadd_prog, &testing::launch_config(BUF_HALF, BLOCK_VADD), (
            b_after_attn_buf.as_device_ptr() as *mut f32,
            ffn1_bn_buf.as_device_ptr() as *mut f32,
            b_final_buf.as_device_ptr() as *mut f32,
            BUF_HALF as i32,
        ))?;

        // ── Stage 5: ChannelCat(a, b_final) → (B, 256, H, W) ────────────────────
        let cat_buf = device.buffer::<f32>(BUF_CAT)?;

        device.launch(&cat_prog, &ch_cfg, (
            a_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            C as i32, C1 as i32, 0i32,         // a → ch [0, 128)
        ))?;
        device.launch(&cat_prog, &ch_cfg, (
            b_final_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            C as i32, C1 as i32, C as i32,     // b → ch [128, 256)
        ))?;

        // ── Stage 6: cv2 Conv(256→256, 1×1) → BN(256) → SiLU ────────────────────
        let mut cat_host = vec![0.0f32; BUF_CAT];
        cat_buf.to_host(&mut cat_host)?;

        let cv2_nc_host = conv1_nc_to_nc_host!(cat_host, C1, C1, cv2_conv_w);

        let mut cv2_nc_buf = device.buffer::<f32>(BUF_CAT)?;
        cv2_nc_buf.to_device(&cv2_nc_host)?;

        let cv2_bn_buf = run_bn!(cv2_nc_buf, C1, cv2_bn_w, cv2_bn_b, cv2_bn_rm, cv2_bn_rv);

        let cv2_silu = device.buffer::<f32>(BUF_CAT)?;
        device.launch(&silu_prog, &testing::launch_config(BUF_CAT, BLOCK_SILU), (
            cv2_bn_buf.as_device_ptr() as *mut f32,
            cv2_silu.as_device_ptr() as *mut f32,
            BUF_CAT as i32,
        ))?;

        // ── Compare ───────────────────────────────────────────────────────────────
        // GPU output is NC; expected is NCHW → convert for index alignment.
        let mut y_nc = vec![0.0f32; BUF_CAT];
        cv2_silu.to_host(&mut y_nc)?;
        let expected_nc = nchw_to_nc(&expected, BATCH, C1, H, W);

        for i in 0..BUF_CAT {
            assert!(
                (y_nc[i] - expected_nc[i]).abs() < 1e-3,
                "c2psa mismatch at element {i}: gpu={} expected={}",
                y_nc[i], expected_nc[i],
            );
        }

        Ok(())
    }
}
