/*
 * SpinorML Ltd 🚀 AGPL-3.0 License - https://spinorml.com/license
 */

// End-to-end CUDA tests for Concat (forward + backward) and Upsample
// (forward + backward) in NCHW layout.
//
// Concat dimensions: B=2, C0=16, C1=16, C_total=32, H=4, W=4
//   The channel_cat kernel operates in NC layout with N=B, C=C*H*W,
//   so the NCHW tensor is treated as N=2 "rows" each of C*H*W elements.
//
// Upsample dimensions: B=2, C=16, H=4, W=4, SCALE=2, OH=8, OW=8
//
// Fixtures generated by tests/fixtures/concat_upsample/generate.py.

#[cfg(feature = "cuda")]
mod cuda {
    use dotenv::dotenv;
    use serial_test::serial;
    use teeny_compiler::compiler::{driver::cuda::compile_kernel, target::cuda::Target};
    use teeny_core::device::{Device, buffer::Buffer};
    use teeny_cuda::{device::CudaLaunchConfig, errors::Result, testing};

    // ── Dimensions ────────────────────────────────────────────────────────────
    const B:       usize = 2;
    const C0:      usize = 16;
    const C1:      usize = 16;
    const C_TOTAL: usize = C0 + C1; // 32
    const H:       usize = 4;
    const W:       usize = 4;

    // Upsample
    const C_UP:    usize = 16;
    const SCALE:   i32   = 2;
    const OH:      usize = H * SCALE as usize; // 8
    const OW:      usize = W * SCALE as usize; // 8

    // NC-layout interpretation for NCHW concat: N=B, C=C_i*H*W
    const CHUNK_C0_NC: i32 = (C0 * H * W) as i32; // 256
    const CHUNK_C1_NC: i32 = (C1 * H * W) as i32; // 256
    const C_TOTAL_NC:  i32 = (C_TOTAL * H * W) as i32; // 512

    const BLOCK_CH:  i32 = 128;
    const BLOCK_OW:  i32 = 4;

    fn load(name: &str) -> Vec<f32> {
        let path = format!(
            "{}/tests/fixtures/concat_upsample/{}",
            env!("CARGO_MANIFEST_DIR"),
            name
        );
        let bytes = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
        bytes.chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect()
    }

    // ── Concat forward ────────────────────────────────────────────────────────

    #[test]
    #[serial]
    fn test_concat_forward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;

        let x0 = load("x0.bin");
        let x1 = load("x1.bin");
        let expected = load("expected_cat.bin");

        assert_eq!(x0.len(), B * C0 * H * W);
        assert_eq!(x1.len(), B * C1 * H * W);
        assert_eq!(expected.len(), B * C_TOTAL * H * W);

        let mut x0_buf = device.buffer::<f32>(x0.len())?;
        let mut x1_buf = device.buffer::<f32>(x1.len())?;
        let y_buf = device.buffer::<f32>(B * C_TOTAL * H * W)?;
        x0_buf.to_device(&x0)?;
        x1_buf.to_device(&x1)?;

        let kernel = teeny_kernels::nn::tensor::channel_cat::ChannelCatForward::<f32>::new(BLOCK_CH);
        let target = Target::new(env.capability);
        let ptx = std::fs::read(compile_kernel(&kernel, &target, true)?)?;
        let program = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_cat::ChannelCatForward<f32>,
        >(&ptx)?;

        // Grid: N * ceil(chunk_c / BLOCK_CH) where N = B
        let num_c_tiles_0 = (CHUNK_C0_NC as usize).div_ceil(BLOCK_CH as usize);
        let cfg = CudaLaunchConfig {
            grid:  [(B * num_c_tiles_0) as u32, 1, 1],
            block: [BLOCK_CH as u32, 1, 1],
            cluster: [1, 1, 1],
        };

        // Scatter x0 → channels [0, CHUNK_C0_NC)
        device.launch(&program, &cfg, (
            x0_buf.as_device_ptr() as *mut f32,
            y_buf.as_device_ptr() as *mut f32,
            CHUNK_C0_NC, C_TOTAL_NC, 0i32,
        ))?;

        // Scatter x1 → channels [CHUNK_C0_NC, C_TOTAL_NC)
        let num_c_tiles_1 = (CHUNK_C1_NC as usize).div_ceil(BLOCK_CH as usize);
        let cfg1 = CudaLaunchConfig {
            grid:  [(B * num_c_tiles_1) as u32, 1, 1],
            block: [BLOCK_CH as u32, 1, 1],
            cluster: [1, 1, 1],
        };
        device.launch(&program, &cfg1, (
            x1_buf.as_device_ptr() as *mut f32,
            y_buf.as_device_ptr() as *mut f32,
            CHUNK_C1_NC, C_TOTAL_NC, CHUNK_C0_NC,
        ))?;

        let mut y = vec![0.0f32; B * C_TOTAL * H * W];
        y_buf.to_host(&mut y)?;

        for i in 0..y.len() {
            assert_eq!(y[i], expected[i],
                "concat fwd mismatch at {i}: got={} expected={}", y[i], expected[i]);
        }
        Ok(())
    }

    // ── Concat backward ───────────────────────────────────────────────────────

    #[test]
    #[serial]
    fn test_concat_backward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;

        let dy = load("dy.bin");
        let exp_dx0 = load("expected_dx0.bin");
        let exp_dx1 = load("expected_dx1.bin");

        assert_eq!(dy.len(), B * C_TOTAL * H * W);
        assert_eq!(exp_dx0.len(), B * C0 * H * W);
        assert_eq!(exp_dx1.len(), B * C1 * H * W);

        let mut dy_buf  = device.buffer::<f32>(dy.len())?;
        let dx0_buf = device.buffer::<f32>(B * C0 * H * W)?;
        let dx1_buf = device.buffer::<f32>(B * C1 * H * W)?;
        dy_buf.to_device(&dy)?;

        let kernel = teeny_kernels::nn::tensor::channel_cat::ChannelCatBackward::<f32>::new(BLOCK_CH);
        let target = Target::new(env.capability);
        let ptx = std::fs::read(compile_kernel(&kernel, &target, true)?)?;
        let program = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_cat::ChannelCatBackward<f32>,
        >(&ptx)?;

        let num_c_tiles = (CHUNK_C0_NC as usize).div_ceil(BLOCK_CH as usize);
        let cfg = CudaLaunchConfig {
            grid:  [(B * num_c_tiles) as u32, 1, 1],
            block: [BLOCK_CH as u32, 1, 1],
            cluster: [1, 1, 1],
        };

        device.launch(&program, &cfg, (
            dy_buf.as_device_ptr() as *mut f32,
            dx0_buf.as_device_ptr() as *mut f32,
            CHUNK_C0_NC, C_TOTAL_NC, 0i32,
        ))?;
        device.launch(&program, &cfg, (
            dy_buf.as_device_ptr() as *mut f32,
            dx1_buf.as_device_ptr() as *mut f32,
            CHUNK_C1_NC, C_TOTAL_NC, CHUNK_C0_NC,
        ))?;

        let mut dx0 = vec![0.0f32; B * C0 * H * W];
        let mut dx1 = vec![0.0f32; B * C1 * H * W];
        dx0_buf.to_host(&mut dx0)?;
        dx1_buf.to_host(&mut dx1)?;

        for i in 0..dx0.len() {
            assert_eq!(dx0[i], exp_dx0[i],
                "concat bwd dx0 mismatch at {i}: got={} expected={}", dx0[i], exp_dx0[i]);
        }
        for i in 0..dx1.len() {
            assert_eq!(dx1[i], exp_dx1[i],
                "concat bwd dx1 mismatch at {i}: got={} expected={}", dx1[i], exp_dx1[i]);
        }
        Ok(())
    }

    // ── Upsample forward ──────────────────────────────────────────────────────

    #[test]
    #[serial]
    fn test_upsample_forward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;

        let xu = load("xu.bin");
        let expected = load("expected_up.bin");

        assert_eq!(xu.len(), B * C_UP * H * W);
        assert_eq!(expected.len(), B * C_UP * OH * OW);

        let mut x_buf = device.buffer::<f32>(xu.len())?;
        let y_buf = device.buffer::<f32>(B * C_UP * OH * OW)?;
        x_buf.to_device(&xu)?;

        let kernel = teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dForward::<f32>::new(
            SCALE, SCALE, BLOCK_OW,
        );
        let target = Target::new(env.capability);
        let ptx = std::fs::read(compile_kernel(&kernel, &target, true)?)?;
        let program = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dForward<f32>,
        >(&ptx)?;

        let num_ow_tiles = OW.div_ceil(BLOCK_OW as usize);
        let cfg = CudaLaunchConfig {
            grid:  [(B * C_UP * OH * num_ow_tiles) as u32, 1, 1],
            block: [128, 1, 1],
            cluster: [1, 1, 1],
        };
        device.launch(&program, &cfg, (
            x_buf.as_device_ptr() as *mut f32,
            y_buf.as_device_ptr() as *mut f32,
            B as i32, C_UP as i32, H as i32, W as i32, OH as i32, OW as i32,
        ))?;

        let mut y = vec![0.0f32; B * C_UP * OH * OW];
        y_buf.to_host(&mut y)?;

        for i in 0..y.len() {
            assert_eq!(y[i], expected[i],
                "upsample fwd mismatch at {i}: got={} expected={}", y[i], expected[i]);
        }
        Ok(())
    }

    // ── Upsample backward ─────────────────────────────────────────────────────

    #[test]
    #[serial]
    fn test_upsample_backward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;

        let dyu = load("dyu.bin");
        let expected = load("expected_dxu.bin");

        assert_eq!(dyu.len(), B * C_UP * OH * OW);
        assert_eq!(expected.len(), B * C_UP * H * W);

        let mut dy_buf = device.buffer::<f32>(dyu.len())?;
        let dx_buf = device.buffer::<f32>(B * C_UP * H * W)?;
        dy_buf.to_device(&dyu)?;

        let kernel = teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dBackward::<f32>::new(
            SCALE, SCALE, BLOCK_OW,
        );
        let target = Target::new(env.capability);
        let ptx = std::fs::read(compile_kernel(&kernel, &target, true)?)?;
        let program = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dBackward<f32>,
        >(&ptx)?;

        let num_iw_tiles = W.div_ceil(BLOCK_OW as usize);
        let cfg = CudaLaunchConfig {
            grid:  [(B * C_UP * H * num_iw_tiles) as u32, 1, 1],
            block: [128, 1, 1],
            cluster: [1, 1, 1],
        };
        device.launch(&program, &cfg, (
            dy_buf.as_device_ptr() as *mut f32,
            dx_buf.as_device_ptr() as *mut f32,
            B as i32, C_UP as i32, H as i32, W as i32, OH as i32, OW as i32,
        ))?;

        let mut dx = vec![0.0f32; B * C_UP * H * W];
        dx_buf.to_host(&mut dx)?;

        for i in 0..dx.len() {
            assert!(
                (dx[i] - expected[i]).abs() < 1e-5,
                "upsample bwd mismatch at {i}: got={} expected={}", dx[i], expected[i]
            );
        }
        Ok(())
    }
}
