/*
 * Copyright 2026 Teenygrad
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// End-to-end CUDA forward-pass test for the SPPF block.
//
// Parameters: SPPF(c_in=32, c_out=32, k=5)
//
//   c = c_in // 2 = 16
//   cv1:  Conv(32→16, 1×1, s=1, p=0) → BN          (act=False, no SiLU)
//   pool: MaxPool2d(k=5, stride=1, padding=2)  ×3   [same-spatial]
//   cv2:  Conv(64→32, 1×1, s=1, p=0) → BN → SiLU
//
// Data layout conventions:
//   Conv kernel:        NCHW input/output
//   MaxPool2d kernel:   NCHW input/output
//   BN / SiLU kernels:  NC (N = B×H×W, C = channels)
//   ChannelCat kernel:  NCHW-as-NC (N = B, C = c×H×W) for the cat stage
//
// Fixtures generated by tests/fixtures/sppf_yolo26/generate.py using
// ultralytics SPPF in eval() mode as the reference.

#[cfg(feature = "cuda")]
mod cuda {
    use dotenv::dotenv;
    use serial_test::serial;
    use teeny_compiler::compiler::{driver::cuda::compile_kernel, target::cuda::Target};
    use teeny_core::device::{Device, buffer::Buffer};
    use teeny_cuda::{device::CudaLaunchConfig, errors::Result, testing};

    // ── Dimensions ────────────────────────────────────────────────────────────────
    const B:        usize = 2;
    const C_IN:     usize = 32;
    const C_OUT:    usize = 32;
    const H:        usize = 4;
    const W:        usize = 4;

    const C:        usize = C_IN / 2; // 16 — cv1 output channels
    const C_CAT:    usize = 4 * C;    // 64 — cat([y, p1, p2, p3])

    const N_SPATIAL: usize = B * H * W; // 32 — BN-style N

    // Element counts
    const N_CV1:  usize = N_SPATIAL * C;     // 512   (B, C, H, W)
    const N_CAT:  usize = N_SPATIAL * C_CAT; // 2048  (B, 4C, H, W)
    const N_CV2:  usize = N_SPATIAL * C_OUT; // 1024  (B, C_OUT, H, W)

    // Kernel tuning
    const BLOCK_OW:   i32 = 4;
    const BLOCK_BN:   i32 = 128;
    const BLOCK_SILU: i32 = 128;
    const BLOCK_CH:   i32 = 128;
    const BN_EPS:     f32 = 1e-5;

    // MaxPool2d parameters
    const KH: i32 = 5;
    const KW: i32 = 5;
    const SH: i32 = 1;
    const SW: i32 = 1;
    const PH: i32 = 2;
    const PW: i32 = 2;

    fn load(name: &str) -> Vec<f32> {
        let path = format!(
            "{}/tests/fixtures/sppf_yolo26/{}",
            env!("CARGO_MANIFEST_DIR"),
            name
        );
        let bytes = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
        bytes.chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect()
    }

    /// NCHW → NC (N = B×H×W, C = channels)
    fn nchw_to_nc(src: &[f32], b: usize, c: usize, h: usize, w: usize) -> Vec<f32> {
        let mut out = vec![0.0f32; b * h * w * c];
        for bi in 0..b {
            for ci in 0..c {
                for hi in 0..h {
                    for wi in 0..w {
                        let ni = bi * h * w + hi * w + wi;
                        out[ni * c + ci] = src[bi * c * h * w + ci * h * w + hi * w + wi];
                    }
                }
            }
        }
        out
    }

    /// NC (N = B×H×W, C = channels) → NCHW
    fn nc_to_nchw(src: &[f32], b: usize, c: usize, h: usize, w: usize) -> Vec<f32> {
        let mut out = vec![0.0f32; b * c * h * w];
        for bi in 0..b {
            for ci in 0..c {
                for hi in 0..h {
                    for wi in 0..w {
                        let ni = bi * h * w + hi * w + wi;
                        out[bi * c * h * w + ci * h * w + hi * w + wi] = src[ni * c + ci];
                    }
                }
            }
        }
        out
    }

    // ── Test ──────────────────────────────────────────────────────────────────────

    #[test]
    #[serial]
    fn test_sppf_forward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;
        let target = Target::new(env.capability);

        // ── Load fixtures ──────────────────────────────────────────────────────────
        let x_host      = load("x.bin");
        let cv1_conv_w  = load("cv1_conv_w.bin");
        let cv1_bn_w    = load("cv1_bn_w.bin");
        let cv1_bn_b    = load("cv1_bn_b.bin");
        let cv1_bn_rm   = load("cv1_bn_rm.bin");
        let cv1_bn_rv   = load("cv1_bn_rv.bin");
        let cv2_conv_w  = load("cv2_conv_w.bin");
        let cv2_bn_w    = load("cv2_bn_w.bin");
        let cv2_bn_b    = load("cv2_bn_b.bin");
        let cv2_bn_rm   = load("cv2_bn_rm.bin");
        let cv2_bn_rv   = load("cv2_bn_rv.bin");
        let expected    = load("expected_output.bin");

        assert_eq!(x_host.len(),     B * C_IN * H * W);
        assert_eq!(cv1_conv_w.len(), C * C_IN);          // [16, 32, 1, 1]
        assert_eq!(cv2_conv_w.len(), C_OUT * C_CAT);     // [32, 64, 1, 1]
        assert_eq!(expected.len(),   B * C_OUT * H * W);

        // ── Compile kernels ────────────────────────────────────────────────────────
        // Conv 1×1, s=1, p=0
        let conv1_kernel = teeny_kernels::nn::conv::conv2d::Conv2dForward::<f32>::new(
            1, 1, 1, 1, 0, 0, 1, BLOCK_OW,
        );
        let conv1_ptx = std::fs::read(compile_kernel(&conv1_kernel, &target, true)?)?;
        let conv1_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dForward<f32>,
        >(&conv1_ptx)?;

        // MaxPool2d k=5, s=1, p=2
        let pool_kernel = teeny_kernels::nn::pool::maxpool2d::Maxpool2dForward::<f32>::new(
            KH, KW, SH, SW, PH, PW, BLOCK_OW,
        );
        let pool_ptx = std::fs::read(compile_kernel(&pool_kernel, &target, true)?)?;
        let pool_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::pool::maxpool2d::Maxpool2dForward<f32>,
        >(&pool_ptx)?;

        // BatchNorm inference
        let bn_kernel = teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference::<f32>::new(BLOCK_BN);
        let bn_ptx = std::fs::read(compile_kernel(&bn_kernel, &target, true)?)?;
        let bn_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::norm::batchnorm::BatchNormForwardInference<f32>,
        >(&bn_ptx)?;

        // SiLU
        let silu_kernel = teeny_kernels::nn::activation::sigmoid::SiluForward::<f32>::new(BLOCK_SILU);
        let silu_ptx = std::fs::read(compile_kernel(&silu_kernel, &target, true)?)?;
        let silu_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::activation::sigmoid::SiluForward<f32>,
        >(&silu_ptx)?;

        // ChannelCat (NCHW-as-NC, N=B, C=c*H*W per input)
        let cat_kernel =
            teeny_kernels::nn::tensor::channel_cat::ChannelCatForward::<f32>::new(BLOCK_CH);
        let cat_ptx = std::fs::read(compile_kernel(&cat_kernel, &target, true)?)?;
        let cat_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_cat::ChannelCatForward<f32>,
        >(&cat_ptx)?;

        // ── Reusable launch helpers ────────────────────────────────────────────────
        let ow_tiles = W.div_ceil(BLOCK_OW as usize);

        let bn_cfg = |c_ch: usize| CudaLaunchConfig {
            grid: [c_ch as u32, 1, 1], block: [1, 1, 1], cluster: [1, 1, 1],
        };

        // MaxPool2d grid: B×C×OH×num_ow_tiles (OH=OW=H=W since same-padding)
        let pool_ow_tiles = W.div_ceil(BLOCK_OW as usize);
        let pool_cfg = CudaLaunchConfig {
            grid: [(B * C * H * pool_ow_tiles) as u32, 1, 1],
            block: [128, 1, 1],
            cluster: [1, 1, 1],
        };

        // ChannelCat grid: N=B, ceil(chunk_c*H*W / BLOCK_CH) per batch
        let chunk_nc = C * H * W; // 256 elements per batch × input
        let cat_num_tiles = chunk_nc.div_ceil(BLOCK_CH as usize);
        let cat_cfg = CudaLaunchConfig {
            grid: [(B * cat_num_tiles) as u32, 1, 1],
            block: [BLOCK_CH as u32, 1, 1],
            cluster: [1, 1, 1],
        };
        let c_total_nc = (C_CAT * H * W) as i32; // 1024
        let chunk_nc_i = (chunk_nc) as i32;       // 256

        // ── Stage 1: cv1 Conv(32→16, 1×1) ─────────────────────────────────────────
        let mut x_buf      = device.buffer::<f32>(B * C_IN * H * W)?;
        let mut cv1_cw_buf = device.buffer::<f32>(C * C_IN)?;
        let cv1_nchw       = device.buffer::<f32>(N_CV1)?;

        x_buf.to_device(&x_host)?;
        cv1_cw_buf.to_device(&cv1_conv_w)?;

        device.launch(&conv1_prog, &CudaLaunchConfig {
            grid:  [(B * C * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            x_buf.as_device_ptr() as *mut f32,
            cv1_cw_buf.as_device_ptr() as *mut f32,
            cv1_nchw.as_device_ptr() as *mut f32,
            B as i32, C_IN as i32, C as i32,
            H as i32, W as i32, H as i32, W as i32,
        ))?;

        // ── Stage 1b: cv1 BN (act=False — no SiLU, matches ultralytics SPPF) ────────
        let mut tmp = vec![0.0f32; N_CV1];
        cv1_nchw.to_host(&mut tmp)?;
        let cv1_nc_host = nchw_to_nc(&tmp, B, C, H, W);

        let mut cv1_nc_buf  = device.buffer::<f32>(N_CV1)?;
        let cv1_bn_out      = device.buffer::<f32>(N_CV1)?;
        let mut cv1_bnw_buf = device.buffer::<f32>(C)?;
        let mut cv1_bnb_buf = device.buffer::<f32>(C)?;
        let mut cv1_bnrm    = device.buffer::<f32>(C)?;
        let mut cv1_bnrv    = device.buffer::<f32>(C)?;

        cv1_nc_buf.to_device(&cv1_nc_host)?;
        cv1_bnw_buf.to_device(&cv1_bn_w)?;
        cv1_bnb_buf.to_device(&cv1_bn_b)?;
        cv1_bnrm.to_device(&cv1_bn_rm)?;
        cv1_bnrv.to_device(&cv1_bn_rv)?;

        device.launch(&bn_prog, &bn_cfg(C), (
            cv1_nc_buf.as_device_ptr() as *mut f32,
            cv1_bn_out.as_device_ptr() as *mut f32,
            cv1_bnw_buf.as_device_ptr() as *mut f32,
            cv1_bnb_buf.as_device_ptr() as *mut f32,
            cv1_bnrm.as_device_ptr() as *mut f32,
            cv1_bnrv.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, C as i32, BN_EPS,
        ))?;

        // ── Stage 2: Convert NC → NCHW for MaxPool2d ──────────────────────────────
        let mut cv1_bn_nc = vec![0.0f32; N_CV1];
        cv1_bn_out.to_host(&mut cv1_bn_nc)?;
        let y_nchw_host = nc_to_nchw(&cv1_bn_nc, B, C, H, W);

        let mut y_buf = device.buffer::<f32>(N_CV1)?;
        y_buf.to_device(&y_nchw_host)?;

        // ── Stage 3: MaxPool2d × 3 (same-spatial, k=5, s=1, p=2) ─────────────────
        let p1_buf = device.buffer::<f32>(N_CV1)?;
        device.launch(&pool_prog, &pool_cfg, (
            y_buf.as_device_ptr() as *mut f32,
            p1_buf.as_device_ptr() as *mut f32,
            B as i32, C as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;

        let p2_buf = device.buffer::<f32>(N_CV1)?;
        device.launch(&pool_prog, &pool_cfg, (
            p1_buf.as_device_ptr() as *mut f32,
            p2_buf.as_device_ptr() as *mut f32,
            B as i32, C as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;

        let p3_buf = device.buffer::<f32>(N_CV1)?;
        device.launch(&pool_prog, &pool_cfg, (
            p2_buf.as_device_ptr() as *mut f32,
            p3_buf.as_device_ptr() as *mut f32,
            B as i32, C as i32, H as i32, W as i32, H as i32, W as i32,
        ))?;

        // ── Stage 4: ChannelCat([y, p1, p2, p3]) in NCHW-as-NC (N=B, C=c×H×W) ───
        //
        // Each input has chunk_c = C×H×W = 256 elements per batch row.
        // c_total_nc = 4×256 = 1024 per batch row.
        let cat_buf = device.buffer::<f32>(N_CAT)?;

        device.launch(&cat_prog, &cat_cfg, (
            y_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            chunk_nc_i, c_total_nc, 0i32,
        ))?;
        device.launch(&cat_prog, &cat_cfg, (
            p1_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            chunk_nc_i, c_total_nc, chunk_nc_i,
        ))?;
        device.launch(&cat_prog, &cat_cfg, (
            p2_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            chunk_nc_i, c_total_nc, 2 * chunk_nc_i,
        ))?;
        device.launch(&cat_prog, &cat_cfg, (
            p3_buf.as_device_ptr() as *mut f32,
            cat_buf.as_device_ptr() as *mut f32,
            chunk_nc_i, c_total_nc, 3 * chunk_nc_i,
        ))?;

        // ── Stage 5: cv2 Conv(64→32, 1×1) ─────────────────────────────────────────
        // ChannelCat output is in NCHW-as-NC with N=B, effectively NCHW (B, 4C, H, W).
        let mut cv2_cw_buf = device.buffer::<f32>(C_OUT * C_CAT)?;
        let cv2_nchw       = device.buffer::<f32>(N_CV2)?;
        cv2_cw_buf.to_device(&cv2_conv_w)?;

        device.launch(&conv1_prog, &CudaLaunchConfig {
            grid:  [(B * C_OUT * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1], cluster: [1, 1, 1],
        }, (
            cat_buf.as_device_ptr() as *mut f32,
            cv2_cw_buf.as_device_ptr() as *mut f32,
            cv2_nchw.as_device_ptr() as *mut f32,
            B as i32, C_CAT as i32, C_OUT as i32,
            H as i32, W as i32, H as i32, W as i32,
        ))?;

        // ── Stage 5b: cv2 BN + SiLU ───────────────────────────────────────────────
        let mut tmp = vec![0.0f32; N_CV2];
        cv2_nchw.to_host(&mut tmp)?;
        let cv2_nc_host = nchw_to_nc(&tmp, B, C_OUT, H, W);

        let mut cv2_nc_buf  = device.buffer::<f32>(N_CV2)?;
        let cv2_bn_out      = device.buffer::<f32>(N_CV2)?;
        let mut cv2_bnw_buf = device.buffer::<f32>(C_OUT)?;
        let mut cv2_bnb_buf = device.buffer::<f32>(C_OUT)?;
        let mut cv2_bnrm    = device.buffer::<f32>(C_OUT)?;
        let mut cv2_bnrv    = device.buffer::<f32>(C_OUT)?;

        cv2_nc_buf.to_device(&cv2_nc_host)?;
        cv2_bnw_buf.to_device(&cv2_bn_w)?;
        cv2_bnb_buf.to_device(&cv2_bn_b)?;
        cv2_bnrm.to_device(&cv2_bn_rm)?;
        cv2_bnrv.to_device(&cv2_bn_rv)?;

        device.launch(&bn_prog, &bn_cfg(C_OUT), (
            cv2_nc_buf.as_device_ptr() as *mut f32,
            cv2_bn_out.as_device_ptr() as *mut f32,
            cv2_bnw_buf.as_device_ptr() as *mut f32,
            cv2_bnb_buf.as_device_ptr() as *mut f32,
            cv2_bnrm.as_device_ptr() as *mut f32,
            cv2_bnrv.as_device_ptr() as *mut f32,
            N_SPATIAL as i32, C_OUT as i32, BN_EPS,
        ))?;

        let cv2_silu = device.buffer::<f32>(N_CV2)?;
        device.launch(&silu_prog, &testing::launch_config(N_CV2, BLOCK_SILU), (
            cv2_bn_out.as_device_ptr() as *mut f32,
            cv2_silu.as_device_ptr() as *mut f32,
            N_CV2 as i32,
        ))?;

        // ── Compare ───────────────────────────────────────────────────────────────
        // GPU output is NC (N=B*H*W, C=C_OUT); convert expected NCHW → NC for comparison.
        let mut y_nc = vec![0.0f32; N_CV2];
        cv2_silu.to_host(&mut y_nc)?;
        let expected_nc = nchw_to_nc(&expected, B, C_OUT, H, W);

        for i in 0..N_CV2 {
            assert!(
                (y_nc[i] - expected_nc[i]).abs() < 1e-3,
                "sppf mismatch at element {i}: gpu={} expected={}",
                y_nc[i], expected_nc[i],
            );
        }

        Ok(())
    }
}
