/*
 * SpinorML Ltd 🚀 AGPL-3.0 License - https://spinorml.com/license
 */

// C2PSA block backward-pass CUDA test.
//
// Verifies the full backward pass of C2PSA(c1=256, c2=256, n=1, e=0.5) in
// training mode by comparing the computed dx against PyTorch autograd reference.
//
// Fixtures from tests/fixtures/c2psa_yolo26/backward/ contain:
//   - x, dy, dx_expected
//   - Per-stage (×7): pre_bn_nc, bn_mean, bn_rstd, pre_silu_nc, conv_w, bn_w
//   - FA2 tensors: q, k, v_lo, v_hi, o_lo, o_hi, L
//
// Backward order:
//   cv2 SiLU↓ → cv2 BN↓ → cv2 Conv1×1 Dx
//   → cat↓ → [d_a, d_b_final]
//   → ffn shortcut: d_b_after_attn += d_b_final
//   → ffn1 BN↓ → ffn1 Conv1×1 Dx → ffn0 SiLU↓ → ffn0 BN↓ → ffn0 Conv1×1 Dx
//   → accumulate d_b_after_attn
//   → proj BN↓ → proj Conv1×1 Dx → d_x_attn
//   → pe BN↓ → pe DW Conv3×3 Dx → d_v_nchw_from_pe
//   → FA2 backward lo+hi → dQ, dK, dV
//   → combine d_qkv_bn
//   → qkv BN↓ → qkv Conv1×1 Dx → d_b_from_attn
//   → accumulate d_b
//   → chunk↓ → d_cv1_out
//   → cv1 SiLU↓ → cv1 BN↓ → cv1 Conv1×1 Dx → dx
//
// Fixtures generated by tests/fixtures/c2psa_yolo26/generate_backward.py.

#[cfg(feature = "cuda")]
mod cuda {
    use dotenv::dotenv;
    use serial_test::serial;
    use teeny_compiler::compiler::{driver::cuda::compile_kernel, target::cuda::Target};
    use teeny_core::device::{Device, buffer::Buffer};
    use teeny_cuda::{device::CudaLaunchConfig, errors::Result, testing};

    // ── Dimensions ────────────────────────────────────────────────────────────────
    const BATCH:     usize = 2;
    const C1:        usize = 256;
    const C:         usize = 128;
    const H:         usize = 4;
    const W:         usize = 4;

    const NUM_HEADS: usize = 2;
    const HEAD_DIM:  usize = 64;
    const KEY_DIM:   usize = 32;
    const QKV_H:     usize = 256;
    const HEAD_SPAN: usize = 2 * KEY_DIM + HEAD_DIM;
    const SCALE:     f32   = 0.176_776_7_f32;
    const N:         usize = H * W;
    const N_SPATIAL: usize = BATCH * N;

    const BH:              usize = BATCH * NUM_HEADS;
    const FA2_TENSOR_SIZE: usize = BH * N * KEY_DIM;
    const FA2_L_SIZE:      usize = BH * N;

    const BUF_256: usize = N_SPATIAL * C1;
    const BUF_128: usize = N_SPATIAL * C;

    // ── Kernel tuning ─────────────────────────────────────────────────────────────
    const BLOCK_OW:   i32 = 4;
    const BLOCK_BN:   i32 = 128;
    const BLOCK_SILU: i32 = 128;
    const BLOCK_CH:   i32 = 128;
    const BLOCK_VADD: i32 = 128;

    // ── Fixture loader ────────────────────────────────────────────────────────────

    fn load(name: &str) -> Vec<f32> {
        let path = format!(
            "{}/tests/fixtures/c2psa_yolo26/backward/{}",
            env!("CARGO_MANIFEST_DIR"),
            name
        );
        let bytes = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
        bytes
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect()
    }

    // ── Layout helpers ────────────────────────────────────────────────────────────

    fn nchw_to_nc(src: &[f32], b: usize, c: usize, h: usize, w: usize) -> Vec<f32> {
        let mut out = vec![0.0f32; b * h * w * c];
        for bi in 0..b {
            for ci in 0..c {
                for hi in 0..h {
                    for wi in 0..w {
                        let ni = bi * h * w + hi * w + wi;
                        out[ni * c + ci] = src[bi * c * h * w + ci * h * w + hi * w + wi];
                    }
                }
            }
        }
        out
    }

    fn nc_to_nchw(src: &[f32], b: usize, c: usize, h: usize, w: usize) -> Vec<f32> {
        let mut out = vec![0.0f32; b * c * h * w];
        for bi in 0..b {
            for ci in 0..c {
                for hi in 0..h {
                    for wi in 0..w {
                        let ni = bi * h * w + hi * w + wi;
                        out[bi * c * h * w + ci * h * w + hi * w + wi] = src[ni * c + ci];
                    }
                }
            }
        }
        out
    }

    // NC(N_SPATIAL=32, C=128) → (d_olo, d_ohi) each [BH=4, N=16, KEY_DIM=32].
    // Inverse of fa2_pair_to_nchw∘nchw_to_nc.
    fn nc_to_fa2_pair(d_nc: &[f32]) -> (Vec<f32>, Vec<f32>) {
        let mut d_olo = vec![0.0f32; FA2_TENSOR_SIZE];
        let mut d_ohi = vec![0.0f32; FA2_TENSOR_SIZE];
        for b in 0..BATCH {
            for h in 0..NUM_HEADS {
                let bh = b * NUM_HEADS + h;
                for n in 0..N {
                    let nc_row  = (b * N + n) * C;
                    let fa2_row = bh * N * KEY_DIM + n * KEY_DIM;
                    for d in 0..KEY_DIM {
                        d_olo[fa2_row + d] = d_nc[nc_row + h * HEAD_DIM + d];
                        d_ohi[fa2_row + d] = d_nc[nc_row + h * HEAD_DIM + KEY_DIM + d];
                    }
                }
            }
        }
        (d_olo, d_ohi)
    }

    // Combine dQ, dK [BH=4,N=16,KEY_DIM=32] and dV NCHW [B=2,C=128,H,W]
    // → d_qkv NC (N_SPATIAL=32, QKV_H=256).
    fn combine_dqkv_to_nc(dq: &[f32], dk: &[f32], dv_nchw: &[f32]) -> Vec<f32> {
        let mut out = vec![0.0f32; N_SPATIAL * QKV_H];
        for b in 0..BATCH {
            for h in 0..NUM_HEADS {
                let bh     = b * NUM_HEADS + h;
                let q_ch   = h * HEAD_SPAN;
                let k_ch   = q_ch + KEY_DIM;
                let vlo_ch = k_ch + KEY_DIM;
                let vhi_ch = vlo_ch + KEY_DIM;
                for n in 0..N {
                    let fa2_row = bh * N * KEY_DIM + n * KEY_DIM;
                    let nc_row  = (b * N + n) * QKV_H;
                    for d in 0..KEY_DIM {
                        out[nc_row + q_ch + d] = dq[fa2_row + d];
                        out[nc_row + k_ch + d] = dk[fa2_row + d];
                        let lo_ch = h * HEAD_DIM + d;
                        let hi_ch = h * HEAD_DIM + KEY_DIM + d;
                        out[nc_row + vlo_ch + d] = dv_nchw[b * C * H * W + lo_ch * H * W + n];
                        out[nc_row + vhi_ch + d] = dv_nchw[b * C * H * W + hi_ch * H * W + n];
                    }
                }
            }
        }
        out
    }

    // ── Test ──────────────────────────────────────────────────────────────────────

    #[test]
    #[serial]
    fn test_c2psa_yolo26_backward_cuda() -> Result<()> {
        dotenv().ok();
        let env = testing::setup_cuda_env()?;
        let device = env.device;
        let target = Target::new(env.capability);

        // ── Load fixtures ─────────────────────────────────────────────────────────
        let dy_nchw     = load("dy.bin");
        let dx_expected = load("dx_expected.bin");

        let cv1_conv_w   = load("cv1_conv_w.bin");
        let cv1_bn_w     = load("cv1_bn_w.bin");
        let cv1_pre_bn   = load("cv1_pre_bn_nc.bin");
        let cv1_mean     = load("cv1_bn_mean.bin");
        let cv1_rstd     = load("cv1_bn_rstd.bin");
        let cv1_pre_silu = load("cv1_pre_silu_nc.bin");

        let qkv_conv_w = load("m0_attn_qkv_conv_w.bin");
        let qkv_bn_w   = load("m0_attn_qkv_bn_w.bin");
        let qkv_pre_bn = load("m0_attn_qkv_pre_bn_nc.bin");
        let qkv_mean   = load("m0_attn_qkv_bn_mean.bin");
        let qkv_rstd   = load("m0_attn_qkv_bn_rstd.bin");

        let pe_conv_w  = load("m0_attn_pe_conv_w.bin");
        let pe_bn_w    = load("m0_attn_pe_bn_w.bin");
        let pe_pre_bn  = load("m0_attn_pe_pre_bn_nc.bin");
        let pe_mean    = load("m0_attn_pe_bn_mean.bin");
        let pe_rstd    = load("m0_attn_pe_bn_rstd.bin");

        let proj_conv_w = load("m0_attn_proj_conv_w.bin");
        let proj_bn_w   = load("m0_attn_proj_bn_w.bin");
        let proj_pre_bn = load("m0_attn_proj_pre_bn_nc.bin");
        let proj_mean   = load("m0_attn_proj_bn_mean.bin");
        let proj_rstd   = load("m0_attn_proj_bn_rstd.bin");

        let ffn0_conv_w   = load("m0_ffn0_conv_w.bin");
        let ffn0_bn_w     = load("m0_ffn0_bn_w.bin");
        let ffn0_pre_bn   = load("m0_ffn0_pre_bn_nc.bin");
        let ffn0_mean     = load("m0_ffn0_bn_mean.bin");
        let ffn0_rstd     = load("m0_ffn0_bn_rstd.bin");
        let ffn0_pre_silu = load("m0_ffn0_pre_silu_nc.bin");

        let ffn1_conv_w = load("m0_ffn1_conv_w.bin");
        let ffn1_bn_w   = load("m0_ffn1_bn_w.bin");
        let ffn1_pre_bn = load("m0_ffn1_pre_bn_nc.bin");
        let ffn1_mean   = load("m0_ffn1_bn_mean.bin");
        let ffn1_rstd   = load("m0_ffn1_bn_rstd.bin");

        let cv2_conv_w   = load("cv2_conv_w.bin");
        let cv2_bn_w     = load("cv2_bn_w.bin");
        let cv2_pre_bn   = load("cv2_pre_bn_nc.bin");
        let cv2_mean     = load("cv2_bn_mean.bin");
        let cv2_rstd     = load("cv2_bn_rstd.bin");
        let cv2_pre_silu = load("cv2_pre_silu_nc.bin");

        let q_fa2 = load("attn_q.bin");
        let k_fa2 = load("attn_k.bin");
        let v_lo  = load("attn_v_lo.bin");
        let v_hi  = load("attn_v_hi.bin");
        let o_lo  = load("attn_o_lo.bin");
        let o_hi  = load("attn_o_hi.bin");
        let l_fa2 = load("attn_l.bin");

        // ── Compile kernels ───────────────────────────────────────────────────────

        let conv1_bwd_dx_kernel =
            teeny_kernels::nn::conv::conv2d::Conv2dBackwardDx::<f32>::new(
                1, 1, 1, 1, 0, 0, 1, BLOCK_OW,
            );
        let conv1_bwd_dx_ptx =
            std::fs::read(compile_kernel(&conv1_bwd_dx_kernel, &target, true)?)?;
        let conv1_bwd_dx_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dBackwardDx<f32>,
        >(&conv1_bwd_dx_ptx)?;

        let conv_dw_bwd_dx_kernel =
            teeny_kernels::nn::conv::conv2d::Conv2dBackwardDx::<f32>::new(
                3, 3, 1, 1, 1, 1, C as i32, BLOCK_OW,
            );
        let conv_dw_bwd_dx_ptx =
            std::fs::read(compile_kernel(&conv_dw_bwd_dx_kernel, &target, true)?)?;
        let conv_dw_bwd_dx_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::conv::conv2d::Conv2dBackwardDx<f32>,
        >(&conv_dw_bwd_dx_ptx)?;

        let bn_bwd_kernel =
            teeny_kernels::nn::norm::batchnorm::BatchNormBackward::<f32>::new(BLOCK_BN);
        let bn_bwd_ptx = std::fs::read(compile_kernel(&bn_bwd_kernel, &target, true)?)?;
        let bn_bwd_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::norm::batchnorm::BatchNormBackward<f32>,
        >(&bn_bwd_ptx)?;

        let silu_bwd_kernel =
            teeny_kernels::nn::activation::sigmoid::SiluBackward::new(BLOCK_SILU);
        let silu_bwd_ptx = std::fs::read(compile_kernel(&silu_bwd_kernel, &target, true)?)?;
        let silu_bwd_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::activation::sigmoid::SiluBackward,
        >(&silu_bwd_ptx)?;

        let fa2_dq_kernel =
            teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDq::new(
                KEY_DIM as i32,
            );
        let fa2_dq_ptx = std::fs::read(compile_kernel(&fa2_dq_kernel, &target, true)?)?;
        let fa2_dq_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDq,
        >(&fa2_dq_ptx)?;

        let fa2_dkv_kernel =
            teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDkv::new(
                KEY_DIM as i32,
            );
        let fa2_dkv_ptx = std::fs::read(compile_kernel(&fa2_dkv_kernel, &target, true)?)?;
        let fa2_dkv_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDkv,
        >(&fa2_dkv_ptx)?;

        let vadd_ptx = std::fs::read(compile_kernel(
            &teeny_kernels::math::add::VectorAdd::<f32>::new(BLOCK_VADD),
            &target, true,
        )?)?;
        let vadd_prog = testing::load_program_from_ptx::<
            teeny_kernels::math::add::VectorAdd<f32>,
        >(&vadd_ptx)?;

        let chunk_bwd_kernel =
            teeny_kernels::nn::tensor::channel_chunk::ChannelChunkBackward::<f32>::new(BLOCK_CH);
        let chunk_bwd_ptx =
            std::fs::read(compile_kernel(&chunk_bwd_kernel, &target, true)?)?;
        let chunk_bwd_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_chunk::ChannelChunkBackward<f32>,
        >(&chunk_bwd_ptx)?;

        let cat_bwd_kernel =
            teeny_kernels::nn::tensor::channel_cat::ChannelCatBackward::<f32>::new(BLOCK_CH);
        let cat_bwd_ptx =
            std::fs::read(compile_kernel(&cat_bwd_kernel, &target, true)?)?;
        let cat_bwd_prog = testing::load_program_from_ptx::<
            teeny_kernels::nn::tensor::channel_cat::ChannelCatBackward<f32>,
        >(&cat_bwd_ptx)?;

        // ── Reusable helpers ──────────────────────────────────────────────────────

        let ow_tiles = W.div_ceil(BLOCK_OW as usize);

        // BN backward: (dy_buf [N_SP,C], pre_bn host, bn_w host, mean host, rstd host)
        // → dx_buf [N_SP,C].  Grid: [C,1,1], Block: [1,1,1].
        macro_rules! bn_bwd {
            ($dy_buf:expr, $n_sp:expr, $c:expr,
             $pre_bn:expr, $bn_w:expr, $mean:expr, $rstd:expr) => {{
                let mut x_buf    = device.buffer::<f32>($n_sp * $c)?;
                let mut w_buf    = device.buffer::<f32>($c)?;
                let mut mean_buf = device.buffer::<f32>($c)?;
                let mut rstd_buf = device.buffer::<f32>($c)?;
                x_buf.to_device(&$pre_bn)?;
                w_buf.to_device(&$bn_w)?;
                mean_buf.to_device(&$mean)?;
                rstd_buf.to_device(&$rstd)?;
                let dx_buf    = device.buffer::<f32>($n_sp * $c)?;
                let dw_buf    = device.buffer::<f32>($c)?;
                let dbias_buf = device.buffer::<f32>($c)?;
                device.launch(&bn_bwd_prog, &CudaLaunchConfig {
                    grid: [$c as u32, 1, 1], block: [1, 1, 1], cluster: [1, 1, 1],
                }, (
                    $dy_buf.as_device_ptr() as *mut f32,
                    x_buf.as_device_ptr() as *mut f32,
                    dx_buf.as_device_ptr() as *mut f32,
                    w_buf.as_device_ptr() as *mut f32,
                    mean_buf.as_device_ptr() as *mut f32,
                    rstd_buf.as_device_ptr() as *mut f32,
                    dw_buf.as_device_ptr() as *mut f32,
                    dbias_buf.as_device_ptr() as *mut f32,
                    $n_sp as i32, $c as i32,
                ))?;
                dx_buf
            }};
        }

        // SiLU backward: (dy_buf, pre_silu host, n) → dx_buf
        macro_rules! silu_bwd {
            ($dy_buf:expr, $n:expr, $pre_silu:expr) => {{
                let mut x_buf = device.buffer::<f32>($n)?;
                x_buf.to_device(&$pre_silu)?;
                let dx_buf = device.buffer::<f32>($n)?;
                device.launch(&silu_bwd_prog,
                    &testing::launch_config($n, BLOCK_SILU), (
                    $dy_buf.as_device_ptr() as *mut f32,
                    x_buf.as_device_ptr() as *mut f32,
                    dx_buf.as_device_ptr() as *mut f32,
                    $n as i32,
                ))?;
                dx_buf
            }};
        }

        // Conv1×1 BackwardDx: dy_nc host → dx NC host.
        // Zero-initialises dx before launch (atomic_add accumulates).
        macro_rules! conv1_bwd_dx {
            ($dy_nc:expr, $b:expr, $c_in:expr, $c_out:expr, $w:expr) => {{
                let dy_nchw = nc_to_nchw(&$dy_nc, $b, $c_out, H, W);
                let n_dy = $b * $c_out * H * W;
                let n_w  = $c_out * $c_in;
                let n_dx = $b * $c_in  * H * W;
                let mut dy_buf = device.buffer::<f32>(n_dy)?;
                let mut w_buf  = device.buffer::<f32>(n_w)?;
                let mut dx_buf = device.buffer::<f32>(n_dx)?;
                dy_buf.to_device(&dy_nchw)?;
                w_buf.to_device(&$w)?;
                dx_buf.to_device(&vec![0.0f32; n_dx])?;
                device.launch(&conv1_bwd_dx_prog, &CudaLaunchConfig {
                    grid:  [($b * $c_out * H * ow_tiles) as u32, 1, 1],
                    block: [128, 1, 1],
                    cluster: [1, 1, 1],
                }, (
                    dy_buf.as_device_ptr() as *mut f32,
                    w_buf.as_device_ptr() as *mut f32,
                    dx_buf.as_device_ptr() as *mut f32,
                    $b as i32, $c_in as i32, $c_out as i32,
                    H as i32, W as i32, H as i32, W as i32,
                ))?;
                let mut tmp = vec![0.0f32; n_dx];
                dx_buf.to_host(&mut tmp)?;
                nchw_to_nc(&tmp, $b, $c_in, H, W)
            }};
        }

        // VectorAdd on GPU: returns a + b.
        macro_rules! vadd {
            ($a:expr, $b:expr, $n:expr) => {{
                let out = device.buffer::<f32>($n)?;
                device.launch(&vadd_prog,
                    &testing::launch_config($n, BLOCK_VADD), (
                    $a.as_device_ptr() as *mut f32,
                    $b.as_device_ptr() as *mut f32,
                    out.as_device_ptr() as *mut f32,
                    $n as i32,
                ))?;
                out
            }};
        }

        // ── Upload FA2 forward tensors ────────────────────────────────────────────

        let mut q_buf   = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        let mut k_buf   = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        let mut vlo_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        let mut vhi_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        let mut olo_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        let mut ohi_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        let mut l_buf   = device.buffer::<f32>(FA2_L_SIZE)?;
        q_buf.to_device(&q_fa2)?;
        k_buf.to_device(&k_fa2)?;
        vlo_buf.to_device(&v_lo)?;
        vhi_buf.to_device(&v_hi)?;
        olo_buf.to_device(&o_lo)?;
        ohi_buf.to_device(&o_hi)?;
        l_buf.to_device(&l_fa2)?;

        let fa2_cfg = CudaLaunchConfig {
            grid: [N as u32, BH as u32, 1], block: [128, 1, 1], cluster: [1, 1, 1],
        };
        let ch_cfg = CudaLaunchConfig {
            grid: [N_SPATIAL as u32, 1, 1],
            block: [BLOCK_CH as u32, 1, 1],
            cluster: [1, 1, 1],
        };

        // ── Step 1-3: cv2 SiLU↓ → BN↓ → Conv1×1 Dx ─────────────────────────────

        let dy_nc = nchw_to_nc(&dy_nchw, BATCH, C1, H, W);
        let mut dy_nc_buf = device.buffer::<f32>(BUF_256)?;
        dy_nc_buf.to_device(&dy_nc)?;

        let d_cv2_bn    = silu_bwd!(dy_nc_buf, BUF_256, cv2_pre_silu);
        let d_cv2_conv  = bn_bwd!(d_cv2_bn, N_SPATIAL, C1,
                                  cv2_pre_bn, cv2_bn_w, cv2_mean, cv2_rstd);
        let mut d_cv2_conv_host = vec![0.0f32; BUF_256];
        d_cv2_conv.to_host(&mut d_cv2_conv_host)?;
        let d_cat_nc = conv1_bwd_dx!(d_cv2_conv_host, BATCH, C1, C1, cv2_conv_w);

        // ── Step 4: cat↓ → d_a, d_b_final ───────────────────────────────────────

        let mut d_cat_buf = device.buffer::<f32>(BUF_256)?;
        d_cat_buf.to_device(&d_cat_nc)?;

        let d_a_buf       = device.buffer::<f32>(BUF_128)?;
        let d_b_final_buf = device.buffer::<f32>(BUF_128)?;
        device.launch(&cat_bwd_prog, &ch_cfg, (
            d_cat_buf.as_device_ptr() as *mut f32,
            d_a_buf.as_device_ptr() as *mut f32,
            C as i32, C1 as i32, 0i32,
        ))?;
        device.launch(&cat_bwd_prog, &ch_cfg, (
            d_cat_buf.as_device_ptr() as *mut f32,
            d_b_final_buf.as_device_ptr() as *mut f32,
            C as i32, C1 as i32, C as i32,
        ))?;

        // ── Step 5-10: FFN shortcut + backward ───────────────────────────────────
        // b_final = b_after_attn + ffn1_bn → d_b_after_attn_acc=d_b_final,
        //                                    d_ffn1_bn=d_b_final.

        let d_ffn1_bn   = bn_bwd!(d_b_final_buf, N_SPATIAL, C,
                                  ffn1_pre_bn, ffn1_bn_w, ffn1_mean, ffn1_rstd);
        let mut d_ffn1_host = vec![0.0f32; BUF_128];
        d_ffn1_bn.to_host(&mut d_ffn1_host)?;
        let d_ffn0_silu_nc = conv1_bwd_dx!(d_ffn1_host, BATCH, 2 * C, C, ffn1_conv_w);

        let mut d_ffn0_silu_buf = device.buffer::<f32>(BUF_256)?;
        d_ffn0_silu_buf.to_device(&d_ffn0_silu_nc)?;

        let d_ffn0_bn   = silu_bwd!(d_ffn0_silu_buf, BUF_256, ffn0_pre_silu);
        let d_ffn0_conv = bn_bwd!(d_ffn0_bn, N_SPATIAL, 2 * C,
                                  ffn0_pre_bn, ffn0_bn_w, ffn0_mean, ffn0_rstd);
        let mut d_ffn0_conv_host = vec![0.0f32; BUF_256];
        d_ffn0_conv.to_host(&mut d_ffn0_conv_host)?;
        let d_b_from_ffn_nc = conv1_bwd_dx!(d_ffn0_conv_host, BATCH, C, 2 * C, ffn0_conv_w);

        // ── Step 11: accumulate d_b_after_attn ───────────────────────────────────

        let mut d_b_from_ffn_buf = device.buffer::<f32>(BUF_128)?;
        d_b_from_ffn_buf.to_device(&d_b_from_ffn_nc)?;
        let d_b_after_attn = vadd!(d_b_final_buf, d_b_from_ffn_buf, BUF_128);

        // ── Step 12-14: proj BN↓ → Conv1×1 Dx ───────────────────────────────────
        // b_after_attn = b + proj_bn → d_proj_bn = d_b_after_attn

        let d_proj_bn   = bn_bwd!(d_b_after_attn, N_SPATIAL, C,
                                  proj_pre_bn, proj_bn_w, proj_mean, proj_rstd);
        let mut d_proj_host = vec![0.0f32; BUF_128];
        d_proj_bn.to_host(&mut d_proj_host)?;
        let d_x_attn_nc = conv1_bwd_dx!(d_proj_host, BATCH, C, C, proj_conv_w);

        // ── Step 15-17: pe BN↓ → DW Conv3×3 Dx ──────────────────────────────────
        // x_attn = attn_out + pe_bn → d_pe_bn = d_x_attn

        let mut d_x_attn_buf = device.buffer::<f32>(BUF_128)?;
        d_x_attn_buf.to_device(&d_x_attn_nc)?;

        let d_pe_conv = bn_bwd!(d_x_attn_buf, N_SPATIAL, C,
                                pe_pre_bn, pe_bn_w, pe_mean, pe_rstd);
        let mut d_pe_conv_host = vec![0.0f32; BUF_128];
        d_pe_conv.to_host(&mut d_pe_conv_host)?;

        let d_pe_nchw = nc_to_nchw(&d_pe_conv_host, BATCH, C, H, W);
        let n_v = BATCH * C * H * W;
        let mut d_pe_dy_buf = device.buffer::<f32>(n_v)?;
        let mut pe_w_buf    = device.buffer::<f32>(C * 9)?;
        let mut d_v_pe_buf  = device.buffer::<f32>(n_v)?;
        d_pe_dy_buf.to_device(&d_pe_nchw)?;
        pe_w_buf.to_device(&pe_conv_w)?;
        d_v_pe_buf.to_device(&vec![0.0f32; n_v])?;
        device.launch(&conv_dw_bwd_dx_prog, &CudaLaunchConfig {
            grid:  [(BATCH * C * H * ow_tiles) as u32, 1, 1],
            block: [128, 1, 1],
            cluster: [1, 1, 1],
        }, (
            d_pe_dy_buf.as_device_ptr() as *mut f32,
            pe_w_buf.as_device_ptr() as *mut f32,
            d_v_pe_buf.as_device_ptr() as *mut f32,
            BATCH as i32, C as i32, C as i32,
            H as i32, W as i32, H as i32, W as i32,
        ))?;
        let mut d_v_from_pe_nchw = vec![0.0f32; n_v];
        d_v_pe_buf.to_host(&mut d_v_from_pe_nchw)?;

        // ── Step 18: FA2 backward (lo and hi) ────────────────────────────────────

        let (d_olo_host, d_ohi_host) = nc_to_fa2_pair(&d_x_attn_nc);
        let mut d_olo_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        let mut d_ohi_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        d_olo_buf.to_device(&d_olo_host)?;
        d_ohi_buf.to_device(&d_ohi_host)?;

        let dq_lo_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        device.launch(&fa2_dq_prog, &fa2_cfg, (
            q_buf.as_device_ptr() as *mut f32,
            k_buf.as_device_ptr() as *mut f32,
            vlo_buf.as_device_ptr() as *mut f32,
            olo_buf.as_device_ptr() as *mut f32,
            d_olo_buf.as_device_ptr() as *mut f32,
            l_buf.as_device_ptr() as *mut f32,
            dq_lo_buf.as_device_ptr() as *mut f32,
            N as i32, N as i32, SCALE,
        ))?;

        let dk_lo_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        let dv_lo_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        device.launch(&fa2_dkv_prog, &fa2_cfg, (
            q_buf.as_device_ptr() as *mut f32,
            k_buf.as_device_ptr() as *mut f32,
            vlo_buf.as_device_ptr() as *mut f32,
            olo_buf.as_device_ptr() as *mut f32,
            d_olo_buf.as_device_ptr() as *mut f32,
            l_buf.as_device_ptr() as *mut f32,
            dk_lo_buf.as_device_ptr() as *mut f32,
            dv_lo_buf.as_device_ptr() as *mut f32,
            N as i32, N as i32, SCALE,
        ))?;

        let dq_hi_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        device.launch(&fa2_dq_prog, &fa2_cfg, (
            q_buf.as_device_ptr() as *mut f32,
            k_buf.as_device_ptr() as *mut f32,
            vhi_buf.as_device_ptr() as *mut f32,
            ohi_buf.as_device_ptr() as *mut f32,
            d_ohi_buf.as_device_ptr() as *mut f32,
            l_buf.as_device_ptr() as *mut f32,
            dq_hi_buf.as_device_ptr() as *mut f32,
            N as i32, N as i32, SCALE,
        ))?;

        let dk_hi_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        let dv_hi_buf = device.buffer::<f32>(FA2_TENSOR_SIZE)?;
        device.launch(&fa2_dkv_prog, &fa2_cfg, (
            q_buf.as_device_ptr() as *mut f32,
            k_buf.as_device_ptr() as *mut f32,
            vhi_buf.as_device_ptr() as *mut f32,
            ohi_buf.as_device_ptr() as *mut f32,
            d_ohi_buf.as_device_ptr() as *mut f32,
            l_buf.as_device_ptr() as *mut f32,
            dk_hi_buf.as_device_ptr() as *mut f32,
            dv_hi_buf.as_device_ptr() as *mut f32,
            N as i32, N as i32, SCALE,
        ))?;

        // ── Step 19: combine dQ=dQ_lo+dQ_hi, dK=dK_lo+dK_hi, dV ─────────────────

        let dq_fa2_buf = vadd!(dq_lo_buf, dq_hi_buf, FA2_TENSOR_SIZE);
        let dk_fa2_buf = vadd!(dk_lo_buf, dk_hi_buf, FA2_TENSOR_SIZE);

        let mut dq_host = vec![0.0f32; FA2_TENSOR_SIZE];
        let mut dk_host = vec![0.0f32; FA2_TENSOR_SIZE];
        let mut dv_lo_h = vec![0.0f32; FA2_TENSOR_SIZE];
        let mut dv_hi_h = vec![0.0f32; FA2_TENSOR_SIZE];
        dq_fa2_buf.to_host(&mut dq_host)?;
        dk_fa2_buf.to_host(&mut dk_host)?;
        dv_lo_buf.to_host(&mut dv_lo_h)?;
        dv_hi_buf.to_host(&mut dv_hi_h)?;

        // dV from FA2 in NCHW [B, C=128, H, W]  (same layout as fa2_pair_to_nchw)
        let dv_from_fa2_nchw = {
            let mut out = vec![0.0f32; n_v];
            for bh in 0..BH {
                let b = bh / NUM_HEADS;
                let h = bh % NUM_HEADS;
                for n in 0..N {
                    let fa2_row = bh * N * KEY_DIM + n * KEY_DIM;
                    for d in 0..KEY_DIM {
                        let lo_ch = h * HEAD_DIM + d;
                        let hi_ch = h * HEAD_DIM + KEY_DIM + d;
                        out[b * C * H * W + lo_ch * H * W + n] = dv_lo_h[fa2_row + d];
                        out[b * C * H * W + hi_ch * H * W + n] = dv_hi_h[fa2_row + d];
                    }
                }
            }
            out
        };

        // ── Step 20: d_v_nchw = d_v_from_pe + d_v_from_fa2 ──────────────────────

        let mut dv_fa2_nchw_buf = device.buffer::<f32>(n_v)?;
        let mut dv_pe_nchw_buf  = device.buffer::<f32>(n_v)?;
        dv_fa2_nchw_buf.to_device(&dv_from_fa2_nchw)?;
        dv_pe_nchw_buf.to_device(&d_v_from_pe_nchw)?;
        let d_v_nchw_buf = vadd!(dv_pe_nchw_buf, dv_fa2_nchw_buf, n_v);
        let mut d_v_nchw_host = vec![0.0f32; n_v];
        d_v_nchw_buf.to_host(&mut d_v_nchw_host)?;

        // ── Step 21: combine d_qkv_bn NC ─────────────────────────────────────────

        let d_qkv_nc = combine_dqkv_to_nc(&dq_host, &dk_host, &d_v_nchw_host);

        // ── Step 22-23: qkv BN↓ → Conv1×1 Dx ────────────────────────────────────

        let mut d_qkv_nc_buf = device.buffer::<f32>(N_SPATIAL * QKV_H)?;
        d_qkv_nc_buf.to_device(&d_qkv_nc)?;

        let d_qkv_conv = bn_bwd!(d_qkv_nc_buf, N_SPATIAL, QKV_H,
                                 qkv_pre_bn, qkv_bn_w, qkv_mean, qkv_rstd);
        let mut d_qkv_conv_host = vec![0.0f32; N_SPATIAL * QKV_H];
        d_qkv_conv.to_host(&mut d_qkv_conv_host)?;
        let d_b_from_attn_nc = conv1_bwd_dx!(d_qkv_conv_host, BATCH, C, QKV_H, qkv_conv_w);

        // ── Step 24: d_b = d_b_after_attn (shortcut) + d_b_from_attn ─────────────

        let mut d_b_from_attn_buf = device.buffer::<f32>(BUF_128)?;
        d_b_from_attn_buf.to_device(&d_b_from_attn_nc)?;
        let d_b_nc_buf = vadd!(d_b_after_attn, d_b_from_attn_buf, BUF_128);

        // ── Step 25: chunk↓ → d_cv1_silu_out NC (256 ch) ────────────────────────

        let mut d_cv1_silu_buf = device.buffer::<f32>(BUF_256)?;
        d_cv1_silu_buf.to_device(&vec![0.0f32; BUF_256])?;
        device.launch(&chunk_bwd_prog, &ch_cfg, (
            d_a_buf.as_device_ptr() as *mut f32,
            d_cv1_silu_buf.as_device_ptr() as *mut f32,
            C1 as i32, C as i32, 0i32,
        ))?;
        device.launch(&chunk_bwd_prog, &ch_cfg, (
            d_b_nc_buf.as_device_ptr() as *mut f32,
            d_cv1_silu_buf.as_device_ptr() as *mut f32,
            C1 as i32, C as i32, C as i32,
        ))?;

        // ── Step 26-28: cv1 SiLU↓ → BN↓ → Conv1×1 Dx ───────────────────────────

        let d_cv1_bn    = silu_bwd!(d_cv1_silu_buf, BUF_256, cv1_pre_silu);
        let d_cv1_conv  = bn_bwd!(d_cv1_bn, N_SPATIAL, C1,
                                  cv1_pre_bn, cv1_bn_w, cv1_mean, cv1_rstd);
        let mut d_cv1_conv_host = vec![0.0f32; BUF_256];
        d_cv1_conv.to_host(&mut d_cv1_conv_host)?;
        let dx_nc = conv1_bwd_dx!(d_cv1_conv_host, BATCH, C1, C1, cv1_conv_w);

        // ── Step 29: Compare ──────────────────────────────────────────────────────

        let dx_exp_nc = nchw_to_nc(&dx_expected, BATCH, C1, H, W);
        let tol = 5e-3_f32;

        for i in 0..BUF_256 {
            assert!(
                (dx_nc[i] - dx_exp_nc[i]).abs() < tol,
                "c2psa backward dx mismatch at {i}: got={:.6} expected={:.6}",
                dx_nc[i], dx_exp_nc[i],
            );
        }

        Ok(())
    }
}
